import CoveringCodes.Database.ExplicitCode
import CoveringCodes.Database.ProofMode
import CoveringCodes.Database.Source
import CoveringCodes.Database.Sources.Trivial
import Mathlib.Tactic

/-!
# Known-bound upper certificate for K_16(6,2)

This module formalizes the `gf8_binary_lift_length_six_radius_two_cover`
construction from `q16-n6-r2-10752-known-bound-lean-certificate-notes.md`.

Every `Fin 16` symbol is split into a high `Fin 8` component and a low binary
component.  The high component is the GF(8) length-six code generated by the
archived source, with `512` centers.  The low component is a `21`-row binary
array that realizes every assignment on every four-coordinate subset.

For a target word, the high repair supplies four coordinates where the high
component agrees.  The low binary array then matches the low bits on those same
four coordinates.  The lifted center agrees with the original word on four of
six coordinates, hence has Hamming distance at most two.
-/

namespace CoveringCodes
namespace Database

private structure Quad6 where
  a : Fin 6
  b : Fin 6
  c : Fin 6
  d : Fin 6
deriving DecidableEq, Repr

private def highPart (x : Fin 16) : Fin 8 :=
  ⟨x.val / 2, by omega⟩

private def lowPart (x : Fin 16) : Fin 2 :=
  ⟨x.val % 2, by omega⟩

private def assembleSymbol (high : Fin 8) (low : Fin 2) : Fin 16 :=
  ⟨2 * high.val + low.val, by omega⟩

private theorem assemble_high_low (x : Fin 16) :
    assembleSymbol (highPart x) (lowPart x) = x := by
  apply Fin.ext
  simp [assembleSymbol, highPart, lowPart]
  have h := Nat.mod_add_div x.val 2
  omega

private def gf8AddTable : Array Nat := #[
  0, 1, 2, 3, 4, 5, 6, 7,
  1, 0, 3, 2, 5, 4, 7, 6,
  2, 3, 0, 1, 6, 7, 4, 5,
  3, 2, 1, 0, 7, 6, 5, 4,
  4, 5, 6, 7, 0, 1, 2, 3,
  5, 4, 7, 6, 1, 0, 3, 2,
  6, 7, 4, 5, 2, 3, 0, 1,
  7, 6, 5, 4, 3, 2, 1, 0
]

private def gf8MulTable : Array Nat := #[
  0, 0, 0, 0, 0, 0, 0, 0,
  0, 1, 2, 3, 4, 5, 6, 7,
  0, 2, 4, 6, 3, 1, 7, 5,
  0, 3, 6, 5, 7, 4, 1, 2,
  0, 4, 3, 7, 6, 2, 5, 1,
  0, 5, 1, 4, 2, 7, 3, 6,
  0, 6, 7, 1, 5, 3, 2, 4,
  0, 7, 5, 2, 1, 6, 4, 3
]

private def gf8AddNat (x y : Nat) : Nat :=
  gf8AddTable.getD (x * 8 + y) 0

private def gf8MulNat (x y : Nat) : Nat :=
  gf8MulTable.getD (x * 8 + y) 0

private def gf8Add (x y : Fin 8) : Fin 8 :=
  ⟨gf8AddNat x.val y.val, by
    fin_cases x <;> fin_cases y <;> native_decide⟩

private def gf8Mul (x y : Fin 8) : Fin 8 :=
  ⟨gf8MulNat x.val y.val, by
    fin_cases x <;> fin_cases y <;> native_decide⟩

private abbrev gf8_1 : Fin 8 := ⟨1, by decide⟩
private abbrev gf8_2 : Fin 8 := ⟨2, by decide⟩
private abbrev gf8_3 : Fin 8 := ⟨3, by decide⟩

private def decodeHighFree (idx : Fin 512) : Fin 8 × Fin 8 × Fin 8 :=
  (⟨idx.val / 64, by omega⟩, ⟨(idx.val / 8) % 8, by omega⟩, ⟨idx.val % 8, by omega⟩)

private def highCenter (idx : Fin 512) : QaryWord 8 6 :=
  let x3 := (decodeHighFree idx).1
  let x4 := (decodeHighFree idx).2.1
  let x5 := (decodeHighFree idx).2.2
  let s0 := gf8Add (gf8Add (gf8Mul x3 gf8_1) (gf8Mul x4 gf8_1)) (gf8Mul x5 gf8_1)
  let s1 := gf8Add (gf8Add (gf8Mul x3 gf8_1) (gf8Mul x4 gf8_2)) (gf8Mul x5 gf8_3)
  let s2 := gf8Add (gf8Add (gf8Mul x3 gf8_1) (gf8Mul x4 gf8_3)) (gf8Mul x5 gf8_2)
  fun position =>
    if position.val = 0 then s2
    else if position.val = 1 then s1
    else if position.val = 2 then s0
    else if position.val = 3 then x3
    else if position.val = 4 then x4
    else x5

private def gf8Add4 (a b c d : Fin 8) : Fin 8 :=
  gf8Add (gf8Add (gf8Add a b) c) d

private def highSyndrome (x : QaryWord 8 6) : Fin 512 :=
  let s0 := gf8Add4 (x 2) (x 3) (x 4) (x 5)
  let s1 := gf8Add4 (x 1) (x 3) (gf8Mul (x 4) gf8_2) (gf8Mul (x 5) gf8_3)
  let s2 := gf8Add4 (x 0) (x 3) (gf8Mul (x 4) gf8_3) (gf8Mul (x 5) gf8_2)
  ⟨s0.val * 64 + s1.val * 8 + s2.val, by omega⟩

private def packedHighRepairs : Array Nat := #[
  0, 48, 96, 144, 192, 240, 288, 336, 432, 57, 105, 153,
  201, 249, 297, 345, 480, 58, 106, 154, 202, 250, 298, 346,
  528, 59, 107, 155, 203, 251, 299, 347, 576, 60, 108, 156,
  204, 252, 300, 348, 624, 61, 109, 157, 205, 253, 301, 349,
  672, 62, 110, 158, 206, 254, 302, 350, 720, 63, 111, 159,
  207, 255, 303, 351, 816, 65, 113, 161, 209, 257, 305, 353,
  73, 1200, 169, 121, 265, 217, 361, 313, 177, 129, 81, 1584,
  369, 321, 273, 225, 137, 185, 1968, 89, 329, 377, 233, 281,
  593, 649, 761, 705, 1036, 1918, 946, 1283, 641, 601, 713, 753,
  1871, 989, 907, 1338, 689, 745, 665, 609, 954, 899, 1134, 1820,
  737, 697, 617, 657, 1291, 1330, 1773, 1087, 864, 66, 114, 162,
  210, 258, 306, 354, 450, 937, 554, 1917, 762, 1484, 658, 1006,
  122, 170, 1248, 74, 314, 362, 218, 266, 546, 1823, 458, 843,
  666, 1382, 754, 1092, 322, 370, 226, 274, 130, 178, 1632, 82,
  642, 1476, 746, 1390, 570, 1133, 466, 1721, 234, 282, 330, 378,
  2016, 90, 138, 186, 738, 998, 650, 1100, 474, 1627, 562, 1039,
  912, 67, 115, 163, 211, 259, 307, 355, 451, 889, 1775, 507,
  1093, 755, 619, 1054, 499, 1916, 842, 459, 1430, 611, 763, 1485,
  171, 123, 75, 1296, 363, 315, 267, 219, 595, 1101, 1438, 747,
  1132, 515, 475, 1626, 331, 379, 235, 283, 139, 187, 2064, 91,
  275, 227, 371, 323, 83, 1680, 179, 131, 739, 1046, 1477, 603,
  1673, 467, 523, 991, 960, 68, 116, 164, 212, 260, 308, 356,
  452, 1033, 1523, 716, 652, 1866, 1343, 516, 500, 1531, 1082, 668,
  700, 959, 1817, 468, 372, 324, 276, 228, 180, 132, 84, 1728,
  220, 268, 316, 364, 1344, 76, 124, 172, 644, 1678, 951, 524,
  460, 845, 1147, 708, 692, 1335, 1629, 476, 508, 1139, 894, 660,
  188, 140, 92, 2112, 380, 332, 284, 236, 1008, 69, 117, 165,
  213, 261, 309, 357, 229, 277, 325, 373, 1776, 85, 133, 181,
  501, 717, 1130, 993, 565, 749, 1236, 1867, 549, 765, 1001, 1083,
  517, 701, 1914, 852, 93, 2160, 189, 141, 285, 237, 381, 333,
  269, 221, 365, 317, 77, 1392, 173, 125, 693, 525, 1244, 1679,
  757, 557, 942, 1377, 741, 573, 1726, 860, 709, 509, 1385, 895,
  1056, 70, 118, 166, 214, 262, 310, 358, 382, 334, 286, 238,
  190, 142, 94, 2208, 502, 662, 986, 1137, 1725, 863, 606, 574,
  550, 614, 1145, 1035, 1247, 1676, 654, 526, 598, 566, 1819, 1239,
  892, 1529, 510, 670, 646, 518, 855, 1770, 1521, 941, 558, 622,
  318, 366, 222, 270, 126, 174, 1440, 78, 86, 1824, 182, 134,
  278, 230, 374, 326, 1104, 71, 119, 167, 215, 263, 311, 359,
  455, 1081, 615, 1426, 901, 575, 1724, 703, 287, 239, 383, 335,
  95, 2256, 191, 143, 551, 1434, 711, 987, 1630, 479, 1285, 607,
  599, 909, 471, 1865, 940, 719, 1042, 559, 135, 183, 1872, 87,
  327, 375, 231, 279, 695, 1771, 567, 1293, 1050, 623, 846, 463,
  367, 319, 271, 223, 175, 127, 79, 1488
]

private def highRepairPacked (s : Fin 512) : Nat :=
  packedHighRepairs.getD s.val 0

private def highRepairPos1 (s : Fin 512) : Fin 6 :=
  ⟨(highRepairPacked s / 384) % 6, by omega⟩

private def highRepairVal1 (s : Fin 512) : Fin 8 :=
  ⟨(highRepairPacked s / 48) % 8, by omega⟩

private def highRepairPos2 (s : Fin 512) : Fin 6 :=
  ⟨(highRepairPacked s / 8) % 6, by omega⟩

private def highRepairVal2 (s : Fin 512) : Fin 8 :=
  ⟨highRepairPacked s % 8, by omega⟩

private def highCorrection (s : Fin 512) (position : Fin 6) : Fin 8 :=
  if position = highRepairPos1 s then highRepairVal1 s
  else if position = highRepairPos2 s then highRepairVal2 s
  else 0

private def correctedHigh (x : QaryWord 8 6) (position : Fin 6) : Fin 8 :=
  gf8Add (x position) (highCorrection (highSyndrome x) position)

private def highRepairIndex (x : QaryWord 8 6) : Fin 512 :=
  ⟨(correctedHigh x 3).val * 64 + (correctedHigh x 4).val * 8 + (correctedHigh x 5).val,
    by omega⟩

private def highRepair (x : QaryWord 8 6) : QaryWord 8 6 :=
  highCenter (highRepairIndex x)

private def unpackQuad (value : Nat) : Quad6 where
  a := ⟨(value / 216) % 6, by omega⟩
  b := ⟨(value / 36) % 6, by omega⟩
  c := ⟨(value / 6) % 6, by omega⟩
  d := ⟨value % 6, by omega⟩

private def packedHighRepairQuads : Array Nat := #[
  51, 310, 310, 310, 310, 310, 310, 310, 94, 569, 569, 569,
  569, 569, 569, 569, 94, 569, 569, 569, 569, 569, 569, 569,
  94, 569, 569, 569, 569, 569, 569, 569, 94, 569, 569, 569,
  569, 569, 569, 569, 94, 569, 569, 569, 569, 569, 569, 569,
  94, 569, 569, 569, 569, 569, 569, 569, 94, 569, 569, 569,
  569, 569, 569, 569, 58, 353, 353, 353, 353, 353, 353, 353,
  317, 52, 317, 317, 317, 317, 317, 317, 311, 311, 311, 51,
  311, 311, 311, 311, 310, 310, 51, 310, 310, 310, 310, 310,
  137, 101, 94, 95, 65, 51, 59, 53, 137, 101, 94, 95,
  51, 65, 58, 52, 137, 101, 94, 95, 58, 59, 65, 51,
  137, 101, 94, 95, 52, 53, 51, 65, 58, 353, 353, 353,
  353, 353, 353, 353, 137, 65, 101, 51, 94, 52, 95, 58,
  317, 317, 52, 317, 317, 317, 317, 317, 137, 51, 101, 65,
  94, 53, 95, 59, 311, 311, 311, 311, 311, 311, 51, 311,
  137, 53, 101, 52, 94, 65, 95, 51, 310, 310, 310, 310,
  51, 310, 310, 310, 137, 59, 101, 58, 94, 51, 95, 65,
  58, 353, 353, 353, 353, 353, 353, 353, 137, 65, 51, 101,
  59, 95, 94, 58, 137, 51, 65, 101, 53, 95, 94, 52,
  317, 317, 317, 52, 317, 317, 317, 317, 137, 58, 52, 101,
  65, 95, 94, 51, 310, 310, 310, 310, 310, 310, 51, 310,
  311, 311, 311, 311, 311, 51, 311, 311, 137, 59, 53, 101,
  51, 95, 94, 65, 58, 353, 353, 353, 353, 353, 353, 353,
  137, 65, 53, 94, 101, 51, 52, 95, 137, 52, 65, 94,
  101, 58, 51, 95, 311, 311, 311, 311, 311, 311, 311, 51,
  317, 317, 317, 317, 52, 317, 317, 317, 137, 51, 59, 94,
  101, 65, 58, 95, 137, 53, 51, 94, 101, 59, 65, 95,
  310, 310, 310, 51, 310, 310, 310, 310, 58, 353, 353, 353,
  353, 353, 353, 353, 311, 311, 311, 311, 51, 311, 311, 311,
  137, 94, 65, 59, 95, 101, 53, 51, 137, 94, 58, 65,
  95, 101, 51, 59, 310, 51, 310, 310, 310, 310, 310, 310,
  317, 317, 317, 317, 317, 52, 317, 317, 137, 94, 52, 51,
  95, 101, 65, 53, 137, 94, 51, 58, 95, 101, 52, 65,
  58, 353, 353, 353, 353, 353, 353, 353, 310, 310, 310, 310,
  310, 310, 310, 51, 137, 95, 65, 59, 51, 58, 101, 94,
  137, 95, 58, 65, 52, 51, 101, 94, 137, 95, 51, 53,
  65, 52, 101, 94, 137, 95, 59, 51, 53, 65, 101, 94,
  317, 317, 317, 317, 317, 317, 52, 317, 311, 51, 311, 311,
  311, 311, 311, 311, 58, 353, 353, 353, 353, 353, 353, 353,
  137, 65, 95, 53, 59, 94, 51, 101, 310, 310, 310, 310,
  310, 51, 310, 310, 137, 52, 95, 65, 51, 94, 53, 101,
  137, 58, 95, 51, 65, 94, 59, 101, 311, 311, 51, 311,
  311, 311, 311, 311, 137, 51, 95, 52, 58, 94, 65, 101,
  317, 317, 317, 317, 317, 317, 317, 52
]

private def highRepairQuad (s : Fin 512) : Quad6 :=
  unpackQuad (packedHighRepairQuads.getD s.val 51)

private theorem highRepairQuad_distinct :
    ∀ s : Fin 512,
      let q := highRepairQuad s
      q.a ≠ q.b ∧ q.a ≠ q.c ∧ q.a ≠ q.d ∧
        q.b ≠ q.c ∧ q.b ≠ q.d ∧ q.c ≠ q.d := by
  native_decide

set_option maxRecDepth 20000 in
set_option maxHeartbeats 8000000 in
private theorem highRepair_quad_spec :
    ∀ x : QaryWord 8 6,
      let q := highRepairQuad (highSyndrome x)
      x q.a = highRepair x q.a ∧ x q.b = highRepair x q.b ∧
        x q.c = highRepair x q.c ∧ x q.d = highRepair x q.d := by
  native_decide

private def bitFromPacked (value place : Nat) : Fin 2 :=
  ⟨(value / place) % 2, by omega⟩

private def packedLowRows : Array Nat := #[
  1, 2, 4, 8, 15, 16, 23, 27, 29, 30, 32, 39, 43, 45, 46, 51, 53, 54, 57,
  58, 60
]

private def lowRow (idx : Fin 21) : QaryWord 2 6 :=
  let value := packedLowRows.getD idx.val 1
  fun position =>
    if position.val = 0 then bitFromPacked value 32
    else if position.val = 1 then bitFromPacked value 16
    else if position.val = 2 then bitFromPacked value 8
    else if position.val = 3 then bitFromPacked value 4
    else if position.val = 4 then bitFromPacked value 2
    else bitFromPacked value 1

private def firstMatchingLowRowIndex
    (q : Quad6) (a b c d : Fin 2) (idx fuel : Nat) : Fin 21 :=
  match fuel with
  | 0 => 0
  | fuel + 1 =>
      if hidx : idx < 21 then
        if lowRow ⟨idx, hidx⟩ q.a = a ∧ lowRow ⟨idx, hidx⟩ q.b = b ∧
            lowRow ⟨idx, hidx⟩ q.c = c ∧ lowRow ⟨idx, hidx⟩ q.d = d then
          ⟨idx, hidx⟩
        else
          firstMatchingLowRowIndex q a b c d (idx + 1) fuel
      else
        0

set_option maxRecDepth 10000 in
private theorem firstMatchingLowRowIndex_spec :
    ∀ s : Fin 512, ∀ a b c d : Fin 2,
      let q := highRepairQuad s
      let row := firstMatchingLowRowIndex q a b c d 0 21
      lowRow row q.a = a ∧ lowRow row q.b = b ∧
        lowRow row q.c = c ∧ lowRow row q.d = d := by
  native_decide

private def q16Center (highIdx : Fin 512) (lowIdx : Fin 21) : QaryWord 16 6 :=
  fun position => assembleSymbol (highCenter highIdx position) (lowRow lowIdx position)

private def q16Code : Finset (QaryWord 16 6) :=
  (Finset.univ : Finset (Fin 512 × Fin 21)).image (fun p => q16Center p.1 p.2)

private theorem q16Code_card :
    q16Code.card ≤ 10752 := by
  calc
    q16Code.card ≤ (Finset.univ : Finset (Fin 512 × Fin 21)).card := by
      simpa [q16Code] using
        Finset.card_image_le (s := (Finset.univ : Finset (Fin 512 × Fin 21)))
    _ = 10752 := by
      simp

private def q16RepairIndex (x : QaryWord 16 6) : Fin 512 × Fin 21 :=
  let highTarget : QaryWord 8 6 := fun position => highPart (x position)
  let syndrome := highSyndrome highTarget
  let highIdx := highRepairIndex highTarget
  let q := highRepairQuad syndrome
  let lowIdx := firstMatchingLowRowIndex q
    (lowPart (x q.a)) (lowPart (x q.b)) (lowPart (x q.c)) (lowPart (x q.d)) 0 21
  (highIdx, lowIdx)

private def q16Repair (x : QaryWord 16 6) : QaryWord 16 6 :=
  q16Center (q16RepairIndex x).1 (q16RepairIndex x).2

private theorem hammingDist_le_two_of_four_matches
    (x c : QaryWord 16 6) (i j k l : Fin 6)
    (hij : i ≠ j) (hik : i ≠ k) (hil : i ≠ l)
    (hjk : j ≠ k) (hjl : j ≠ l) (hkl : k ≠ l)
    (hi : x i = c i) (hj : x j = c j) (hk : x k = c k) (hl : x l = c l) :
    hammingDist x c ≤ 2 := by
  classical
  let bad : Finset (Fin 6) := Finset.univ.filter (fun position => x position ≠ c position)
  let matched : Finset (Fin 6) := {i, j, k, l}
  have hbad_subset : bad ⊆ Finset.univ \ matched := by
    intro position hposition
    have hne : x position ≠ c position := (Finset.mem_filter.mp hposition).2
    have hnot : position ∉ matched := by
      intro hmem
      simp [matched] at hmem
      rcases hmem with hmem | hmem | hmem | hmem
      · subst hmem
        exact hne hi
      · subst hmem
        exact hne hj
      · subst hmem
        exact hne hk
      · subst hmem
        exact hne hl
    exact Finset.mem_sdiff.mpr ⟨Finset.mem_univ position, hnot⟩
  have hmatched_card : matched.card = 4 := by
    simp [matched, hij, hik, hil, hjk, hjl, hkl]
  have hsdiff_card : (Finset.univ \ matched).card = 2 := by
    rw [Finset.card_sdiff_of_subset]
    · simp [hmatched_card]
    · intro position _
      exact Finset.mem_univ position
  calc
    hammingDist x c = bad.card := rfl
    _ ≤ (Finset.univ \ matched).card := Finset.card_le_card hbad_subset
    _ = 2 := hsdiff_card

set_option maxRecDepth 20000 in
private theorem q16Repair_mem (x : QaryWord 16 6) :
    q16Repair x ∈ q16Code := by
  exact Finset.mem_image.mpr ⟨q16RepairIndex x, Finset.mem_univ _, rfl⟩

private theorem q16Repair_dist (x : QaryWord 16 6) :
    hammingDist x (q16Repair x) ≤ 2 := by
  let highTarget : QaryWord 8 6 := fun position => highPart (x position)
  let syndrome := highSyndrome highTarget
  let highIdx := highRepairIndex highTarget
  let q := highRepairQuad syndrome
  let lowIdx := firstMatchingLowRowIndex q
    (lowPart (x q.a)) (lowPart (x q.b)) (lowPart (x q.c)) (lowPart (x q.d)) 0 21
  have hhigh := highRepair_quad_spec highTarget
  have hlow := firstMatchingLowRowIndex_spec syndrome
    (lowPart (x q.a)) (lowPart (x q.b)) (lowPart (x q.c)) (lowPart (x q.d))
  have hlow_a : lowRow lowIdx q.a = lowPart (x q.a) := by
    simpa [lowIdx, syndrome, q] using hlow.1
  have hlow_b : lowRow lowIdx q.b = lowPart (x q.b) := by
    simpa [lowIdx, syndrome, q] using hlow.2.1
  have hlow_c : lowRow lowIdx q.c = lowPart (x q.c) := by
    simpa [lowIdx, syndrome, q] using hlow.2.2.1
  have hlow_d : lowRow lowIdx q.d = lowPart (x q.d) := by
    simpa [lowIdx, syndrome, q] using hlow.2.2.2
  have hdistinct := highRepairQuad_distinct syndrome
  have hhigh_a : highCenter highIdx q.a = highPart (x q.a) := by
    simpa [highTarget, highRepair, highIdx, syndrome, q] using hhigh.1.symm
  have hhigh_b : highCenter highIdx q.b = highPart (x q.b) := by
    simpa [highTarget, highRepair, highIdx, syndrome, q] using hhigh.2.1.symm
  have hhigh_c : highCenter highIdx q.c = highPart (x q.c) := by
    simpa [highTarget, highRepair, highIdx, syndrome, q] using hhigh.2.2.1.symm
  have hhigh_d : highCenter highIdx q.d = highPart (x q.d) := by
    simpa [highTarget, highRepair, highIdx, syndrome, q] using hhigh.2.2.2.symm
  have ha : x q.a = q16Center highIdx lowIdx q.a := by
    simpa [q16Center, hhigh_a, hlow_a] using
      (assemble_high_low (x q.a)).symm
  have hb : x q.b = q16Center highIdx lowIdx q.b := by
    simpa [q16Center, hhigh_b, hlow_b] using
      (assemble_high_low (x q.b)).symm
  have hc : x q.c = q16Center highIdx lowIdx q.c := by
    simpa [q16Center, hhigh_c, hlow_c] using
      (assemble_high_low (x q.c)).symm
  have hd : x q.d = q16Center highIdx lowIdx q.d := by
    simpa [q16Center, hhigh_d, hlow_d] using
      (assemble_high_low (x q.d)).symm
  have hdist := hammingDist_le_two_of_four_matches x (q16Center highIdx lowIdx)
    q.a q.b q.c q.d hdistinct.1 hdistinct.2.1 hdistinct.2.2.1 hdistinct.2.2.2.1
    hdistinct.2.2.2.2.1 hdistinct.2.2.2.2.2 ha hb hc hd
  simpa [q16Repair, q16RepairIndex, highTarget, syndrome, highIdx, q, lowIdx] using hdist

set_option maxRecDepth 20000 in
private theorem q16Code_covers :
    CoversFinset q16Code 2 := by
  intro x
  exact ⟨q16Repair x, q16Repair_mem x, q16Repair_dist x⟩

private def q16Explicit : ExplicitQaryUpper 16 6 2 10752 :=
  { code := q16Code
    card_le := q16Code_card
    covers := q16Code_covers }

private theorem knownBoundQ16N6R2Cert :
    QaryKUpper 16 6 2 10752 :=
  q16Explicit.toUpper

def knownBoundQ16N6R2UpperName : String :=
  "lean_known_bounds_q16_n6_r2_gf8_binary_lift"

def knownBoundQ16N6R2Upper (q n r : Nat) : Nat :=
  if q = 16 ∧ n = 6 ∧ r = 2 then 10752 else trivialUpper q n r

theorem knownBoundQ16N6R2Upper_valid (q n r : Nat) :
    QaryKUpper q n r (knownBoundQ16N6R2Upper q n r) := by
  by_cases h : q = 16 ∧ n = 6 ∧ r = 2
  · rcases h with ⟨rfl, rfl, rfl⟩
    simpa [knownBoundQ16N6R2Upper] using knownBoundQ16N6R2Cert
  · simpa [knownBoundQ16N6R2Upper, h] using trivialUpper_valid q n r

def knownBoundQ16N6R2UpperSource : UpperBoundSource where
  value := knownBoundQ16N6R2Upper
  trace := fun q n r =>
    .primitive knownBoundQ16N6R2UpperName (knownBoundQ16N6R2Upper_valid q n r)

end Database
end CoveringCodes
