import CoveringCodes.Database.Sources.LRATNative

/-!
# K16 e01 Split LRAT Smoke

This file is generated by `scripts/k16_generate_split_lrat_lean.py`.
It replays selected split LRAT leaves with the native RUP checker.
-/

namespace CoveringCodes
namespace Database

open LRATNative
open Std.Internal

private def e01CoreCnfText : String :=
  include_str "../../../data/K_16_4_2/lrat/core/profile_lower_e01_not_block_sequential_core.cnf"

private def e01CoreParsed : Prod Nat LRATNative.RawCnf :=
  (LRATNative.parseDimacsFull? e01CoreCnfText).getD (0, #[])

private abbrev e01CoreNVars : Nat := e01CoreParsed.1
private abbrev e01CoreCnf : LRATNative.RawCnf := e01CoreParsed.2

private def e01_top_0001_lratText : String :=
  include_str "../../../data/K_16_4_2/lrat/split_prefix_core/e01_core_prefix_001_r00_c00.lrat"

private def e01_top_0001_lratSteps : Array Mathlib.Tactic.Sat.LRATStep :=
  (LRATNative.parseLRAT? e01_top_0001_lratText).getD #[]

private def e01_top_0001_leaf : LRATNative.ParsedCubeLRAT :=
  { cube := [1], steps := e01_top_0001_lratSteps }

private def e01_top_0002_lratText : String :=
  include_str "../../../data/K_16_4_2/lrat/split_prefix_core/e01_core_prefix_002_r00_c01.lrat"

private def e01_top_0002_lratSteps : Array Mathlib.Tactic.Sat.LRATStep :=
  (LRATNative.parseLRAT? e01_top_0002_lratText).getD #[]

private def e01_top_0002_leaf : LRATNative.ParsedCubeLRAT :=
  { cube := [-1, 2], steps := e01_top_0002_lratSteps }

private def e01_top_0003_lratText : String :=
  include_str "../../../data/K_16_4_2/lrat/split_prefix_core/e01_core_prefix_003_r00_c02.lrat"

private def e01_top_0003_lratSteps : Array Mathlib.Tactic.Sat.LRATStep :=
  (LRATNative.parseLRAT? e01_top_0003_lratText).getD #[]

private def e01_top_0003_leaf : LRATNative.ParsedCubeLRAT :=
  { cube := [-1, -2, 3], steps := e01_top_0003_lratSteps }

private def e01_top_0004_lratText : String :=
  include_str "../../../data/K_16_4_2/lrat/split_prefix_core/e01_core_prefix_004_r00_c03.lrat"

private def e01_top_0004_lratSteps : Array Mathlib.Tactic.Sat.LRATStep :=
  (LRATNative.parseLRAT? e01_top_0004_lratText).getD #[]

private def e01_top_0004_leaf : LRATNative.ParsedCubeLRAT :=
  { cube := [-1, -2, -3, 4], steps := e01_top_0004_lratSteps }

private def e01_top_0005_lratText : String :=
  include_str "../../../data/K_16_4_2/lrat/split_prefix_core/e01_core_prefix_005_r00_c04.lrat"

private def e01_top_0005_lratSteps : Array Mathlib.Tactic.Sat.LRATStep :=
  (LRATNative.parseLRAT? e01_top_0005_lratText).getD #[]

private def e01_top_0005_leaf : LRATNative.ParsedCubeLRAT :=
  { cube := [-1, -2, -3, -4, 5], steps := e01_top_0005_lratSteps }

private def e01Leaves : List LRATNative.ParsedCubeLRAT :=
  [e01_top_0001_leaf, e01_top_0002_leaf, e01_top_0003_leaf, e01_top_0004_leaf, e01_top_0005_leaf]

set_option maxHeartbeats 2000000 in
private theorem e01Leaves_checked :
    LRATNative.checkParsedCubeLRATs e01CoreNVars e01CoreCnf e01Leaves = true := by
  native_decide

set_option maxHeartbeats 2000000 in
private theorem e01_top_0001_unsat :
    forall v : Sat.Valuation,
      Sat.Valuation.satisfies_fmla v
        (LRATNative.rawCnfToSat
          (LRATNative.rawCnfAppendCube e01CoreCnf [1])) ->
        False := by
  simpa [e01_top_0001_leaf] using
    (LRATNative.checkParsedCubeLRATs_branch_unsat_of_mem
      (nvars := e01CoreNVars) (cnf := e01CoreCnf)
      (leaf := e01_top_0001_leaf) (leaves := e01Leaves)
      e01Leaves_checked (by simp [e01Leaves]))

set_option maxHeartbeats 2000000 in
private theorem e01_top_0002_unsat :
    forall v : Sat.Valuation,
      Sat.Valuation.satisfies_fmla v
        (LRATNative.rawCnfToSat
          (LRATNative.rawCnfAppendCube e01CoreCnf [-1, 2])) ->
        False := by
  simpa [e01_top_0002_leaf] using
    (LRATNative.checkParsedCubeLRATs_branch_unsat_of_mem
      (nvars := e01CoreNVars) (cnf := e01CoreCnf)
      (leaf := e01_top_0002_leaf) (leaves := e01Leaves)
      e01Leaves_checked (by simp [e01Leaves]))

set_option maxHeartbeats 2000000 in
private theorem e01_top_0003_unsat :
    forall v : Sat.Valuation,
      Sat.Valuation.satisfies_fmla v
        (LRATNative.rawCnfToSat
          (LRATNative.rawCnfAppendCube e01CoreCnf [-1, -2, 3])) ->
        False := by
  simpa [e01_top_0003_leaf] using
    (LRATNative.checkParsedCubeLRATs_branch_unsat_of_mem
      (nvars := e01CoreNVars) (cnf := e01CoreCnf)
      (leaf := e01_top_0003_leaf) (leaves := e01Leaves)
      e01Leaves_checked (by simp [e01Leaves]))

set_option maxHeartbeats 2000000 in
private theorem e01_top_0004_unsat :
    forall v : Sat.Valuation,
      Sat.Valuation.satisfies_fmla v
        (LRATNative.rawCnfToSat
          (LRATNative.rawCnfAppendCube e01CoreCnf [-1, -2, -3, 4])) ->
        False := by
  simpa [e01_top_0004_leaf] using
    (LRATNative.checkParsedCubeLRATs_branch_unsat_of_mem
      (nvars := e01CoreNVars) (cnf := e01CoreCnf)
      (leaf := e01_top_0004_leaf) (leaves := e01Leaves)
      e01Leaves_checked (by simp [e01Leaves]))

set_option maxHeartbeats 2000000 in
private theorem e01_top_0005_unsat :
    forall v : Sat.Valuation,
      Sat.Valuation.satisfies_fmla v
        (LRATNative.rawCnfToSat
          (LRATNative.rawCnfAppendCube e01CoreCnf [-1, -2, -3, -4, 5])) ->
        False := by
  simpa [e01_top_0005_leaf] using
    (LRATNative.checkParsedCubeLRATs_branch_unsat_of_mem
      (nvars := e01CoreNVars) (cnf := e01CoreCnf)
      (leaf := e01_top_0005_leaf) (leaves := e01Leaves)
      e01Leaves_checked (by simp [e01Leaves]))

end Database
end CoveringCodes
