import CoveringCodes.Database.Sources.LRATNative

/-!
# Direct K16 support-defect CNF mirror

This file mirrors the unsorted `support_le5` instance generated by
`scripts/k16_present_profile_sat.py --kind support_le5 --coord 0
--threshold-encoding sequential`.

The variables are pair-present variables, threshold variables `y(i,a,t)` for
`t = 6..16`, sequential counters forcing thresholds from pair-present degrees,
four excess-budget counters, and one support-at-most-five counter for
coordinate `0`.
-/

namespace CoveringCodes
namespace Database
namespace HexadecimaryFourTwoSupportDirect

open LRATNative

def q : Nat := 16
def coordCount : Nat := 4
def pairCount : Nat := 6
def thresholdCount : Nat := 11
def excessBudget : Nat := 6

def pairIndices : List (Nat × Nat) :=
  [(0, 1), (0, 2), (0, 3), (1, 2), (1, 3), (2, 3)]

def presentVarCount : Nat := pairCount * q * q
def thresholdVarCount : Nat := coordCount * q * thresholdCount
def thresholdCounterBlockCount : Nat := q * (q + 1) / 2
def thresholdCounterVarCount : Nat :=
  coordCount * q * (coordCount - 1) * thresholdCounterBlockCount

def thresholdCounterStart : Nat := presentVarCount + thresholdVarCount + 1
def budgetCounterStart : Nat :=
  presentVarCount + thresholdVarCount + thresholdCounterVarCount + 1

def presentVar (pairIndex left right : Nat) : Nat :=
  pairIndex * q * q + left * q + right + 1

def posPresentLit (pairIndex left right : Nat) : Int :=
  Int.ofNat (presentVar pairIndex left right)

def pairIndexOf (left right : Nat) : Nat :=
  match left, right with
  | 0, 1 => 0
  | 0, 2 => 1
  | 0, 3 => 2
  | 1, 2 => 3
  | 1, 3 => 4
  | 2, 3 => 5
  | _, _ => 0

def incidentPresentLits (coord symbol other : Nat) : List Int :=
  if coord < other then
    (List.range q).map (fun b =>
      posPresentLit (pairIndexOf coord other) symbol b)
  else
    (List.range q).map (fun b =>
      posPresentLit (pairIndexOf other coord) b symbol)

def thresholdVar (coord symbol threshold : Nat) : Nat :=
  presentVarCount + coord * q * thresholdCount +
    symbol * thresholdCount + (threshold - 6) + 1

def thresholdLit (coord symbol threshold : Nat) : Int :=
  Int.ofNat (thresholdVar coord symbol threshold)

def thresholdVarsForCoord (coord : Nat) : List Int :=
  (List.range q).flatMap (fun symbol =>
    (List.range thresholdCount).map (fun off =>
      thresholdLit coord symbol (off + 6)))

def supportVarsForCoord (coord : Nat) : List Int :=
  (List.range q).map (fun symbol => thresholdLit coord symbol 6)

def supportPrefixCoord0Clauses : List RawClause :=
  (List.range (q - 5)).map (fun off =>
    [-(thresholdLit 0 (off + 5) 6)].toArray)

def sortedThresholdProfileClauses : List RawClause :=
  (List.range coordCount).flatMap (fun coord =>
    (List.range (q - 1)).flatMap (fun prev =>
      (List.range thresholdCount).map (fun off =>
        let symbol := prev + 1
        let threshold := off + 6
        [-(thresholdLit coord symbol threshold),
          thresholdLit coord prev threshold].toArray)))

def sortedSupportLe5Coord0Clauses : List RawClause :=
  [[-(thresholdLit 0 5 6)].toArray]

def otherSlot (coord other : Nat) : Nat :=
  if other < coord then other else other - 1

def thresholdCounterFirst (coord symbol other : Nat) : Nat :=
  thresholdCounterStart +
    ((coord * q + symbol) * (coordCount - 1) + otherSlot coord other) *
      thresholdCounterBlockCount

def triangularPrefix (i : Nat) : Nat :=
  (i - 1) * i / 2

def thresholdCounterVar (coord symbol other i count : Nat) : Nat :=
  thresholdCounterFirst coord symbol other + triangularPrefix i + (count - 1)

def thresholdCounterLit (coord symbol other i count : Nat) : Int :=
  Int.ofNat (thresholdCounterVar coord symbol other i count)

def litAt (lits : List Int) (idx : Nat) : Int :=
  lits.getD idx 0

def thresholdSequentialClausesFor (coord symbol other : Nat) : List RawClause :=
  let lits := incidentPresentLits coord symbol other
  (List.range q).flatMap (fun i0 =>
    let i := i0 + 1
    let lit := litAt lits (i - 1)
    let head : List RawClause :=
      [[-lit, thresholdCounterLit coord symbol other i 1].toArray]
    let carry : List RawClause :=
      if i = 1 then
        []
      else
        (List.range (i - 1)).map (fun c0 =>
          let count := c0 + 1
          [-(thresholdCounterLit coord symbol other (i - 1) count),
            thresholdCounterLit coord symbol other i count].toArray)
    let increment : List RawClause :=
      if i = 1 then
        []
      else
        (List.range (i - 1)).map (fun c0 =>
          let count := c0 + 2
          [-lit, -(thresholdCounterLit coord symbol other (i - 1) (count - 1)),
            thresholdCounterLit coord symbol other i count].toArray)
    head ++ carry ++ increment) ++
  (List.range thresholdCount).map (fun off =>
    let threshold := off + 6
    [-(thresholdCounterLit coord symbol other q threshold),
      thresholdLit coord symbol threshold].toArray)

def thresholdSequentialClauses : List RawClause :=
  (List.range coordCount).flatMap (fun coord =>
    (List.range q).flatMap (fun symbol =>
      (List.range coordCount).flatMap (fun other =>
        if other = coord then
          []
        else
          thresholdSequentialClausesFor coord symbol other)))

def coverageClauses : List RawClause :=
  (List.range q).flatMap (fun a =>
    (List.range q).flatMap (fun b =>
      (List.range q).flatMap (fun c =>
        (List.range q).map (fun d =>
          [posPresentLit 0 a b,
           posPresentLit 1 a c,
           posPresentLit 2 a d,
           posPresentLit 3 b c,
           posPresentLit 4 b d,
           posPresentLit 5 c d].toArray))))

structure CnfBuilder where
  varCount : Nat
  clauses : RawCnf

abbrev CnfM := StateM CnfBuilder

def addClauses (clauses : List RawClause) : CnfM Unit := do
  for clause in clauses do
    modify fun st => { st with clauses := st.clauses.push clause }

def reserveVars (count : Nat) : CnfM Nat := do
  let st ← get
  let first := st.varCount + 1
  set { st with varCount := st.varCount + count }
  pure first

def seqAux (first bound i j : Nat) : Int :=
  Int.ofNat (first + (i - 1) * bound + (j - 1))

def atMostSeqClausesWithAux (first : Nat) (lits : List Int) (bound : Nat) :
    List RawClause :=
  let n := lits.length
  (List.range (n - 1)).map (fun i0 =>
    let i := i0 + 1
    [-(litAt lits (i - 1)), seqAux first bound i 1].toArray) ++
  (List.range (n - 2)).flatMap (fun i0 =>
    let i := i0 + 2
    (List.range bound).map (fun j0 =>
      let j := j0 + 1
      [-(seqAux first bound (i - 1) j), seqAux first bound i j].toArray)) ++
  (List.range (n - 1)).map (fun i0 =>
    let i := i0 + 2
    [-(litAt lits (i - 1)), -(seqAux first bound (i - 1) bound)].toArray) ++
  (List.range (n - 2)).flatMap (fun i0 =>
    let i := i0 + 2
    (List.range (bound - 1)).map (fun j0 =>
      let j := j0 + 2
      [-(litAt lits (i - 1)), -(seqAux first bound (i - 1) (j - 1)),
        seqAux first bound i j].toArray))

def atMostSeqClauses (first : Nat) (lits : List Int) (bound : Nat) :
    List RawClause :=
  let n := lits.length
  if n ≤ bound then
    []
  else if bound = 0 then
    lits.map (fun lit => [-lit].toArray)
  else
    atMostSeqClausesWithAux first lits bound

def atMostSeqAuxCount (lits : List Int) (bound : Nat) : Nat :=
  let n := lits.length
  if n ≤ bound then 0 else if bound = 0 then 0 else (n - 1) * bound

def addAtMost (lits : List Int) (bound : Nat) : CnfM Unit := do
  let n := lits.length
  if n ≤ bound then
    pure ()
  else if bound = 0 then
    addClauses (atMostSeqClauses 0 lits bound)
  else
    let first ← reserveVars (atMostSeqAuxCount lits bound)
    addClauses (atMostSeqClauses first lits bound)

def build (body : CnfM Unit) : CnfBuilder :=
  (body.run
    { varCount := presentVarCount + thresholdVarCount + thresholdCounterVarCount
      clauses := #[] }).2

def supportLe5Coord0SequentialBuilder : CnfBuilder :=
  build do
    addClauses coverageClauses
    addClauses thresholdSequentialClauses
    for coord in List.range coordCount do
      addAtMost (thresholdVarsForCoord coord) excessBudget
    addAtMost (supportVarsForCoord 0) 5

def supportLe5Coord0SequentialCnf : RawCnf :=
  supportLe5Coord0SequentialBuilder.clauses

def supportLe5Coord0SequentialNVars : Nat :=
  supportLe5Coord0SequentialBuilder.varCount

def supportPrefixCoord0SequentialBuilder : CnfBuilder :=
  build do
    addClauses coverageClauses
    addClauses thresholdSequentialClauses
    for coord in List.range coordCount do
      addAtMost (thresholdVarsForCoord coord) excessBudget
    addClauses supportPrefixCoord0Clauses

def supportPrefixCoord0SequentialCnf : RawCnf :=
  supportPrefixCoord0SequentialBuilder.clauses

def supportPrefixCoord0SequentialNVars : Nat :=
  supportPrefixCoord0SequentialBuilder.varCount

def supportSortedCoord0SequentialBuilder : CnfBuilder :=
  build do
    addClauses coverageClauses
    addClauses thresholdSequentialClauses
    for coord in List.range coordCount do
      addAtMost (thresholdVarsForCoord coord) excessBudget
    addClauses sortedThresholdProfileClauses
    addClauses sortedSupportLe5Coord0Clauses

def budgetSequentialClauses : List RawClause :=
  (List.range coordCount).flatMap (fun coord =>
    atMostSeqClauses (budgetCounterStart + coord * ((q * thresholdCount - 1) * excessBudget))
      (thresholdVarsForCoord coord) excessBudget)

def supportSortedCoord0SequentialClauses : List RawClause :=
  coverageClauses ++ thresholdSequentialClauses ++ budgetSequentialClauses ++
    sortedThresholdProfileClauses ++ sortedSupportLe5Coord0Clauses

def supportSortedCoord0SequentialCnf : RawCnf :=
  supportSortedCoord0SequentialClauses.toArray

def supportSortedCoord0SequentialNVars : Nat :=
  supportSortedCoord0SequentialBuilder.varCount

theorem supportSortedCoord0SequentialCnf_toList_eq_sections :
    supportSortedCoord0SequentialCnf.toList =
      coverageClauses ++ thresholdSequentialClauses ++ budgetSequentialClauses ++
        sortedThresholdProfileClauses ++ sortedSupportLe5Coord0Clauses := by
  simp [supportSortedCoord0SequentialCnf, supportSortedCoord0SequentialClauses]

def supportLe5Coord0SequentialCnfText : String :=
  include_str "../../../data/K_16_4_2/lrat/present_profile_support_le5_coord0_sequential.cnf"

def supportPrefixCoord0SequentialCnfText : String :=
  include_str "../../../data/K_16_4_2/lrat/present_profile_support_le5_prefix_coord0_sequential.cnf"

def supportSortedCoord0SequentialCnfText : String :=
  include_str "../../../data/K_16_4_2/lrat/present_profile_support_le5_sorted_coord0_sequential.cnf"

def supportLe5Coord0SequentialParsed : Prod Nat RawCnf :=
  (LRATNative.parseDimacsFull? supportLe5Coord0SequentialCnfText).getD (0, #[])

def supportPrefixCoord0SequentialParsed : Prod Nat RawCnf :=
  (LRATNative.parseDimacsFull? supportPrefixCoord0SequentialCnfText).getD (0, #[])

def supportSortedCoord0SequentialParsed : Prod Nat RawCnf :=
  (LRATNative.parseDimacsFull? supportSortedCoord0SequentialCnfText).getD (0, #[])

abbrev supportLe5Coord0SequentialParsedNVars : Nat :=
  supportLe5Coord0SequentialParsed.1

abbrev supportLe5Coord0SequentialParsedCnf : RawCnf :=
  supportLe5Coord0SequentialParsed.2

abbrev supportPrefixCoord0SequentialParsedNVars : Nat :=
  supportPrefixCoord0SequentialParsed.1

abbrev supportPrefixCoord0SequentialParsedCnf : RawCnf :=
  supportPrefixCoord0SequentialParsed.2

abbrev supportSortedCoord0SequentialParsedNVars : Nat :=
  supportSortedCoord0SequentialParsed.1

abbrev supportSortedCoord0SequentialParsedCnf : RawCnf :=
  supportSortedCoord0SequentialParsed.2

set_option maxHeartbeats 2000000 in
theorem supportLe5Coord0Sequential_nvars_eq_direct :
    supportLe5Coord0SequentialParsedNVars =
      supportLe5Coord0SequentialNVars := by
  native_decide

set_option maxHeartbeats 2000000 in
theorem supportLe5Coord0Sequential_cnf_eq_direct :
    supportLe5Coord0SequentialParsedCnf =
      supportLe5Coord0SequentialCnf := by
  native_decide

set_option maxHeartbeats 2000000 in
theorem supportPrefixCoord0Sequential_nvars_eq_direct :
    supportPrefixCoord0SequentialParsedNVars =
      supportPrefixCoord0SequentialNVars := by
  native_decide

set_option maxHeartbeats 2000000 in
theorem supportPrefixCoord0Sequential_cnf_eq_direct :
    supportPrefixCoord0SequentialParsedCnf =
      supportPrefixCoord0SequentialCnf := by
  native_decide

set_option maxHeartbeats 2000000 in
theorem supportSortedCoord0Sequential_nvars_eq_direct :
    supportSortedCoord0SequentialParsedNVars =
      supportSortedCoord0SequentialNVars := by
  native_decide

set_option maxHeartbeats 2000000 in
theorem supportSortedCoord0Sequential_cnf_eq_direct :
    supportSortedCoord0SequentialParsedCnf =
      supportSortedCoord0SequentialCnf := by
  native_decide

end HexadecimaryFourTwoSupportDirect
end Database
end CoveringCodes
