import CoveringCodes.Database.Sources.LRATNative

/-!
# K16 not-global Split LRAT Smoke

This file is generated by `scripts/k16_generate_split_lrat_lean.py`.
It replays selected split LRAT leaves with the native RUP checker.
-/

namespace CoveringCodes
namespace Database

open LRATNative
open Std.Internal

private def notGlobalCoreCnfText : String :=
  include_str "../../../data/K_16_4_2/lrat/core/profile_lower_not_global_block_sequential_core.cnf"

private def notGlobalCoreParsed : Prod Nat LRATNative.RawCnf :=
  (LRATNative.parseDimacsFull? notGlobalCoreCnfText).getD (0, #[])

private abbrev notGlobalCoreNVars : Nat := notGlobalCoreParsed.1
private abbrev notGlobalCoreCnf : LRATNative.RawCnf := notGlobalCoreParsed.2

private def notGlobal_top_0001_lratText : String :=
  include_str "../../../data/K_16_4_2/lrat/split_not_global_prefix_core/not_global_prefix_0001_p1_r00_c00.lrat"

private def notGlobal_top_0001_lratSteps : Array Mathlib.Tactic.Sat.LRATStep :=
  (LRATNative.parseLRAT? notGlobal_top_0001_lratText).getD #[]

private def notGlobal_top_0001_leaf : LRATNative.ParsedCubeLRAT :=
  { cube := [257], steps := notGlobal_top_0001_lratSteps }

private def notGlobalLeaves : List LRATNative.ParsedCubeLRAT :=
  [notGlobal_top_0001_leaf]

set_option maxHeartbeats 2000000 in
private theorem notGlobalLeaves_checked :
    LRATNative.checkParsedCubeLRATs notGlobalCoreNVars notGlobalCoreCnf notGlobalLeaves = true := by
  native_decide

set_option maxHeartbeats 2000000 in
private theorem notGlobal_top_0001_unsat :
    forall v : Sat.Valuation,
      Sat.Valuation.satisfies_fmla v
        (LRATNative.rawCnfToSat
          (LRATNative.rawCnfAppendCube notGlobalCoreCnf [257])) ->
        False := by
  simpa [notGlobal_top_0001_leaf] using
    (LRATNative.checkParsedCubeLRATs_branch_unsat_of_mem
      (nvars := notGlobalCoreNVars) (cnf := notGlobalCoreCnf)
      (leaf := notGlobal_top_0001_leaf) (leaves := notGlobalLeaves)
      notGlobalLeaves_checked (by simp [notGlobalLeaves]))

end Database
end CoveringCodes
