#!/usr/bin/env python3
"""Generate binary block-compression support modules.

The generated Lean file contains exact finite support definitions for the
one-way Schrijver block-compression path.  It does not register numerical
lower bounds and does not assert the final congruence identity by fiat.
"""

from __future__ import annotations

import argparse
from pathlib import Path


WORD_NUM = {
    13: "Thirteen",
}


def lean_nat_name(n: int) -> str:
    if n not in WORD_NUM:
        raise ValueError(f"no Lean name fragment configured for {n}")
    return WORD_NUM[n]


def generate_binary(n: int) -> str:
    if n != 13:
        raise ValueError("currently only the binary length-13 module is generated")
    length_name = lean_nat_name(n)
    name_prefix = f"binaryLength{length_name}"
    title = f"Generated binary length-{n} block-compression support"
    lines = [
        "import CoveringCodes.SDP.GijswijtPolak2025.Generated.BinaryLengthThirteenSupport",
        "",
        "/-!",
        f"# {title}",
        "",
        "This file records exact finite support definitions for the length-13",
        "Schrijver block-compression path.  It is generated support data and",
        "does not register a numerical lower bound.",
        "-/",
        "",
        "namespace CoveringCodes",
        "namespace SDP",
        "namespace GijswijtPolak2025",
        "",
        "noncomputable section",
        "",
        "set_option maxRecDepth 20000",
        "set_option maxHeartbeats 4000000",
        "set_option linter.constructorNameAsVariable false",
        "",
        f"/-- Positive scaling `2^k` for the length-{n} binary Schrijver blocks. -/",
        f"def {name_prefix}BlockScale (idx : BinaryBlockIndex {n}) : Rat :=",
        "  (2 : Rat) ^ idx.k",
        "",
        f"theorem {name_prefix}BlockScale_pos (idx : BinaryBlockIndex {n}) :",
        f"    0 < {name_prefix}BlockScale idx := by",
        f"  unfold {name_prefix}BlockScale",
        "  positivity",
        "",
        f"/-- Left coordinate of Schrijver pair `a` in block `k`. -/",
        f"def {name_prefix}PairLeftCoord",
        f"    (idx : BinaryBlockIndex {n}) (a : Fin idx.k) : Fin {n} :=",
        "  ⟨a.val, by",
        "    have ha := a.isLt",
        "    have hk := idx.hk",
        "    omega⟩",
        "",
        f"/-- Right coordinate of Schrijver pair `a` in block `k`. -/",
        f"def {name_prefix}PairRightCoord",
        f"    (idx : BinaryBlockIndex {n}) (a : Fin idx.k) : Fin {n} :=",
        "  ⟨idx.k + a.val, by",
        "    have ha := a.isLt",
        "    have hk := idx.hk",
        "    omega⟩",
        "",
        f"@[simp] theorem {name_prefix}PairLeftCoord_val",
        f"    (idx : BinaryBlockIndex {n}) (a : Fin idx.k) :",
        f"    ({name_prefix}PairLeftCoord idx a).val = a.val := by",
        "  rfl",
        "",
        f"@[simp] theorem {name_prefix}PairRightCoord_val",
        f"    (idx : BinaryBlockIndex {n}) (a : Fin idx.k) :",
        f"    ({name_prefix}PairRightCoord idx a).val = idx.k + a.val := by",
        "  rfl",
        "",
        f"/-- Coordinates not covered by the first `2k` paired coordinates. -/",
        f"def {name_prefix}BlockFreeCoords (idx : BinaryBlockIndex {n}) :",
        f"    Finset (Fin {n}) :=",
        "  Finset.univ.filter (fun coord => 2 * idx.k <= coord.val)",
        "",
        f"theorem {name_prefix}BlockFreeCoords_card",
        f"    (idx : BinaryBlockIndex {n}) :",
        f"    ({name_prefix}BlockFreeCoords idx).card = {n} - 2 * idx.k := by",
        "  rcases idx with ⟨k, hk⟩",
        "  have hk' : k ≤ 6 := by omega",
        "  interval_cases k <;> native_decide +revert",
        "",
        f"/-- Left coordinates of the paired part of a block. -/",
        f"def {name_prefix}BlockPairedLeftCoords",
        f"    (idx : BinaryBlockIndex {n}) : Finset (Fin {n}) :=",
        f"  Finset.univ.image ({name_prefix}PairLeftCoord idx)",
        "",
        f"theorem {name_prefix}BlockPairedLeftCoords_card",
        f"    (idx : BinaryBlockIndex {n}) :",
        f"    ({name_prefix}BlockPairedLeftCoords idx).card = idx.k := by",
        f"  unfold {name_prefix}BlockPairedLeftCoords",
        "  rw [Finset.card_image_of_injective]",
        "  · simp",
        "  · intro a b h",
        f"    have hval := congrArg (fun x : Fin {n} => x.val) h",
        f"    dsimp [{name_prefix}PairLeftCoord] at hval",
        "    exact Fin.ext hval",
        "",
        f"/-- Right coordinates of the paired part of a block. -/",
        f"def {name_prefix}BlockPairedRightCoords",
        f"    (idx : BinaryBlockIndex {n}) : Finset (Fin {n}) :=",
        f"  Finset.univ.image ({name_prefix}PairRightCoord idx)",
        "",
        f"theorem {name_prefix}BlockPairedRightCoords_card",
        f"    (idx : BinaryBlockIndex {n}) :",
        f"    ({name_prefix}BlockPairedRightCoords idx).card = idx.k := by",
        f"  unfold {name_prefix}BlockPairedRightCoords",
        "  rw [Finset.card_image_of_injective]",
        "  · simp",
        "  · intro a b h",
        f"    have hval := congrArg (fun x : Fin {n} => x.val) h",
        f"    dsimp [{name_prefix}PairRightCoord] at hval",
        "    exact Fin.ext (Nat.add_left_cancel hval)",
        "",
        f"/-- A support chooses exactly one side from every Schrijver pair. -/",
        f"def {name_prefix}PairChoiceValid",
        f"    (idx : BinaryBlockIndex {n}) (S : Finset (Fin {n})) : Prop :=",
        "  forall a : Fin idx.k,",
        f"    ({name_prefix}PairLeftCoord idx a ∈ S ∧",
        f"        {name_prefix}PairRightCoord idx a ∉ S) ∨",
        f"      ({name_prefix}PairLeftCoord idx a ∉ S ∧",
        f"        {name_prefix}PairRightCoord idx a ∈ S)",
        "",
        f"instance {name_prefix}PairChoiceValid_decidable",
        f"    (idx : BinaryBlockIndex {n}) (S : Finset (Fin {n})) :",
        f"    Decidable ({name_prefix}PairChoiceValid idx S) := by",
        f"  unfold {name_prefix}PairChoiceValid",
        "  infer_instance",
        "",
        f"/-- Pair positions where a support chooses the right side. -/",
        f"def {name_prefix}PairRightChoices",
        f"    (idx : BinaryBlockIndex {n}) (S : Finset (Fin {n})) :",
        "    Finset (Fin idx.k) :=",
        f"  Finset.univ.filter (fun a => {name_prefix}PairRightCoord idx a ∈ S)",
        "",
        f"/-- Pair positions where two supports choose the same side. -/",
        f"def {name_prefix}PairSameChoices",
        f"    (idx : BinaryBlockIndex {n})",
        f"    (S T : Finset (Fin {n})) : Finset (Fin idx.k) :=",
        "  Finset.univ.filter (fun a =>",
        f"    ({name_prefix}PairLeftCoord idx a ∈ S ∧",
        f"        {name_prefix}PairLeftCoord idx a ∈ T) ∨",
        f"      ({name_prefix}PairRightCoord idx a ∈ S ∧",
        f"        {name_prefix}PairRightCoord idx a ∈ T))",
        "",
        f"/-- Pair positions where two supports choose opposite sides. -/",
        f"def {name_prefix}PairOppositeChoices",
        f"    (idx : BinaryBlockIndex {n})",
        f"    (S T : Finset (Fin {n})) : Finset (Fin idx.k) :=",
        "  Finset.univ.filter (fun a =>",
        f"    ({name_prefix}PairLeftCoord idx a ∈ S ∧",
        f"        {name_prefix}PairRightCoord idx a ∈ T) ∨",
        f"      ({name_prefix}PairRightCoord idx a ∈ S ∧",
        f"        {name_prefix}PairLeftCoord idx a ∈ T))",
        "",
        f"/-- Free-coordinate part of a support for one block. -/",
        f"def {name_prefix}BlockFreeSupport",
        f"    (idx : BinaryBlockIndex {n}) (S : Finset (Fin {n})) :",
        f"    Finset (Fin {n}) :=",
        f"  S ∩ {name_prefix}BlockFreeCoords idx",
        "",
        f"theorem {name_prefix}BlockFreeSupport_card_of_valid_card",
        f"    (idx : BinaryBlockIndex {n}) (S : Finset (Fin {n}))",
        "    (row : BinaryBlockCoord idx) :",
        f"    {name_prefix}PairChoiceValid idx S ->",
        "    S.card = idx.k + row.val ->",
        f"    ({name_prefix}BlockFreeSupport idx S).card = row.val := by",
        "  rcases idx with ⟨k, hk⟩",
        "  have hk' : k ≤ 6 := by omega",
        "  interval_cases k <;> native_decide +revert",
        "",
        f"theorem {name_prefix}BlockFreeSupport_card_le_free",
        f"    (idx : BinaryBlockIndex {n}) (S : Finset (Fin {n})) :",
        f"    ({name_prefix}BlockFreeSupport idx S).card <= {n} - 2 * idx.k := by",
        f"  have hsubset : {name_prefix}BlockFreeSupport idx S ⊆",
        f"      {name_prefix}BlockFreeCoords idx := by",
        "    intro coord hcoord",
        "    exact (Finset.mem_inter.mp hcoord).2",
        "  have hle := Finset.card_le_card hsubset",
        f"  rw [{name_prefix}BlockFreeCoords_card] at hle",
        "  exact hle",
        "",
        f"/-- Free-coordinate choices with fixed free intersection size. -/",
        f"def {name_prefix}FreeIntersectionChoices",
        f"    (idx : BinaryBlockIndex {n}) (interFree : Nat) :",
        f"    Finset (Finset (Fin {n})) :=",
        f"  ({name_prefix}BlockFreeCoords idx).powersetCard interFree",
        "",
        f"def {name_prefix}FreeSOnlyChoices",
        f"    (idx : BinaryBlockIndex {n}) (I : Finset (Fin {n}))",
        "    (row interFree : Nat) :",
        f"    Finset (Finset (Fin {n})) :=",
        f"  ({name_prefix}BlockFreeCoords idx \\ I).powersetCard",
        "    (row - interFree)",
        "",
        f"def {name_prefix}FreeTOnlyChoices",
        f"    (idx : BinaryBlockIndex {n}) (I P : Finset (Fin {n}))",
        "    (col interFree : Nat) :",
        f"    Finset (Finset (Fin {n})) :=",
        f"  ({name_prefix}BlockFreeCoords idx \\ (I ∪ P)).powersetCard",
        "    (col - interFree)",
        "",
        f"def {name_prefix}FreePairChoices",
        f"    (idx : BinaryBlockIndex {n}) (row col interFree : Nat) :",
        f"    Finset (Sigma (fun _I : Finset (Fin {n}) =>",
        f"      Sigma (fun _P : Finset (Fin {n}) => Finset (Fin {n})))) :=",
        f"  ({name_prefix}FreeIntersectionChoices idx interFree).sigma (fun I =>",
        f"    ({name_prefix}FreeSOnlyChoices idx I row interFree).sigma (fun P =>",
        f"      {name_prefix}FreeTOnlyChoices idx I P col interFree))",
        "",
        f"theorem {name_prefix}FreeTOnlyBase_card",
        f"    (idx : BinaryBlockIndex {n}) {{I P : Finset (Fin {n})}}",
        "    {row interFree : Nat}",
        f"    (hI : I ∈ {name_prefix}FreeIntersectionChoices idx interFree)",
        f"    (hP : P ∈ {name_prefix}FreeSOnlyChoices idx I row interFree)",
        "    (hinter_row : interFree <= row) :",
        f"    ({name_prefix}BlockFreeCoords idx \\ (I ∪ P)).card =",
        f"      {n} - 2 * idx.k - row := by",
        "  have hIinfo := Finset.mem_powersetCard.mp hI",
        "  have hPinfo := Finset.mem_powersetCard.mp hP",
        f"  have hI_subset : I ⊆ {name_prefix}BlockFreeCoords idx := hIinfo.1",
        f"  have hP_subset : P ⊆ {name_prefix}BlockFreeCoords idx \\ I := hPinfo.1",
        f"  have hP_subset_free : P ⊆ {name_prefix}BlockFreeCoords idx := by",
        "    intro coord hcoord",
        "    exact (Finset.mem_sdiff.mp (hP_subset hcoord)).1",
        "  have hdisj : Disjoint I P := by",
        "    rw [Finset.disjoint_left]",
        "    intro coord hIcoord hPcoord",
        "    exact (Finset.mem_sdiff.mp (hP_subset hPcoord)).2 hIcoord",
        f"  have hunion_subset : I ∪ P ⊆ {name_prefix}BlockFreeCoords idx := by",
        "    intro coord hcoord",
        "    rcases Finset.mem_union.mp hcoord with hcoord | hcoord",
        "    · exact hI_subset hcoord",
        "    · exact hP_subset_free hcoord",
        "  have hcard_union : (I ∪ P).card = row := by",
        "    rw [Finset.card_union_of_disjoint hdisj]",
        "    rw [hIinfo.2, hPinfo.2]",
        "    omega",
        "  rw [Finset.card_sdiff_of_subset hunion_subset]",
        f"  rw [{name_prefix}BlockFreeCoords_card, hcard_union]",
        "",
        f"theorem {name_prefix}FreePairChoices_card",
        f"    (idx : BinaryBlockIndex {n}) (row col interFree : Nat)",
        "    (hinter_row : interFree <= row) :",
        f"    ({name_prefix}FreePairChoices idx row col interFree).card =",
        f"      Nat.choose ({n} - 2 * idx.k) interFree *",
        f"        Nat.choose ({n} - 2 * idx.k - interFree) (row - interFree) *",
        f"          Nat.choose ({n} - 2 * idx.k - row) (col - interFree) := by",
        f"  unfold {name_prefix}FreePairChoices",
        "  calc",
        f"    (({name_prefix}FreeIntersectionChoices idx interFree).sigma",
        "        (fun I =>",
        f"          ({name_prefix}FreeSOnlyChoices idx I row interFree).sigma",
        f"            (fun P => {name_prefix}FreeTOnlyChoices idx I P col interFree))).card =",
        f"        ∑ I ∈ {name_prefix}FreeIntersectionChoices idx interFree,",
        f"          (({name_prefix}FreeSOnlyChoices idx I row interFree).sigma",
        f"            (fun P => {name_prefix}FreeTOnlyChoices idx I P col interFree)).card := by",
        "          simp",
        f"    _ = ∑ I ∈ {name_prefix}FreeIntersectionChoices idx interFree,",
        f"          Nat.choose ({n} - 2 * idx.k - interFree) (row - interFree) *",
        f"            Nat.choose ({n} - 2 * idx.k - row) (col - interFree) := by",
        "          apply Finset.sum_congr rfl",
        "          intro I hI",
        "          calc",
        f"            (({name_prefix}FreeSOnlyChoices idx I row interFree).sigma",
        f"                (fun P => {name_prefix}FreeTOnlyChoices idx I P col interFree)).card =",
        f"                ∑ P ∈ {name_prefix}FreeSOnlyChoices idx I row interFree,",
        f"                  ({name_prefix}FreeTOnlyChoices idx I P col interFree).card := by",
        "                  simp",
        f"            _ = ∑ P ∈ {name_prefix}FreeSOnlyChoices idx I row interFree,",
        f"                Nat.choose ({n} - 2 * idx.k - row) (col - interFree) := by",
        "                  apply Finset.sum_congr rfl",
        "                  intro P hP",
        f"                  unfold {name_prefix}FreeTOnlyChoices",
        "                  rw [Finset.card_powersetCard]",
        f"                  rw [{name_prefix}FreeTOnlyBase_card idx hI hP hinter_row]",
        f"            _ = Nat.choose ({n} - 2 * idx.k - interFree) (row - interFree) *",
        f"                Nat.choose ({n} - 2 * idx.k - row) (col - interFree) := by",
        "                  rw [Finset.sum_const, nsmul_eq_mul]",
        f"                  change ({name_prefix}FreeSOnlyChoices idx I row interFree).card *",
        f"                      Nat.choose ({n} - 2 * idx.k - row) (col - interFree) =",
        f"                    Nat.choose ({n} - 2 * idx.k - interFree) (row - interFree) *",
        f"                      Nat.choose ({n} - 2 * idx.k - row) (col - interFree)",
        "                  congr 1",
        f"                  unfold {name_prefix}FreeSOnlyChoices",
        "                  rw [Finset.card_powersetCard]",
        "                  have hIinfo := Finset.mem_powersetCard.mp hI",
        "                  have hcard :",
        f"                      ({name_prefix}BlockFreeCoords idx \\ I).card =",
        f"                        {n} - 2 * idx.k - interFree := by",
        "                    rw [Finset.card_sdiff_of_subset hIinfo.1]",
        f"                    rw [{name_prefix}BlockFreeCoords_card, hIinfo.2]",
        "                  rw [hcard]",
        "    _ =",
        f"        Nat.choose ({n} - 2 * idx.k) interFree *",
        f"          (Nat.choose ({n} - 2 * idx.k - interFree) (row - interFree) *",
        f"            Nat.choose ({n} - 2 * idx.k - row) (col - interFree)) := by",
        "          rw [Finset.sum_const, nsmul_eq_mul]",
        f"          change ({name_prefix}FreeIntersectionChoices idx interFree).card *",
        f"              (Nat.choose ({n} - 2 * idx.k - interFree) (row - interFree) *",
        f"                Nat.choose ({n} - 2 * idx.k - row) (col - interFree)) =",
        f"            Nat.choose ({n} - 2 * idx.k) interFree *",
        f"              (Nat.choose ({n} - 2 * idx.k - interFree) (row - interFree) *",
        f"                Nat.choose ({n} - 2 * idx.k - row) (col - interFree))",
        "          congr 1",
        f"          unfold {name_prefix}FreeIntersectionChoices",
        "          rw [Finset.card_powersetCard]",
        f"          rw [{name_prefix}BlockFreeCoords_card]",
        f"    _ = Nat.choose ({n} - 2 * idx.k) interFree *",
        f"        Nat.choose ({n} - 2 * idx.k - interFree) (row - interFree) *",
        f"          Nat.choose ({n} - 2 * idx.k - row) (col - interFree) := by",
        "          ring",
        "",
        f"/-- Paired-coordinate choices: same positions and right-side choices for `S`. -/",
        f"def {name_prefix}PairPartChoices",
        f"    (idx : BinaryBlockIndex {n}) (same : Nat) :",
        "    Finset (Finset (Fin idx.k) × Finset (Fin idx.k)) :=",
        "  ((Finset.univ : Finset (Fin idx.k)).powersetCard same).product",
        "    (Finset.univ : Finset (Fin idx.k)).powerset",
        "",
        f"theorem {name_prefix}PairPartChoices_card",
        f"    (idx : BinaryBlockIndex {n}) (same : Nat) :",
        f"    ({name_prefix}PairPartChoices idx same).card =",
        "      Nat.choose idx.k same * 2 ^ idx.k := by",
        f"  unfold {name_prefix}PairPartChoices",
        "  change (((Finset.univ : Finset (Fin idx.k)).powersetCard same) ×ˢ",
        "      (Finset.univ : Finset (Fin idx.k)).powerset).card =",
        "    Nat.choose idx.k same * 2 ^ idx.k",
        "  rw [Finset.card_product]",
        "  rw [Finset.card_powersetCard]",
        "  rw [Finset.card_powerset]",
        "  simp",
        "",
        f"def {name_prefix}BlockCoeffSupportCondition",
        f"    (idx : BinaryBlockIndex {n})",
        "    (row col : BinaryBlockCoord idx)",
        f"    (source : BinaryOrbitIndex {n}) (same : Nat) : Prop :=",
        "  let interFree := source.t - same",
        "  source.i = idx.k + row.val ∧ source.j = idx.k + col.val ∧",
        f"    same <= idx.k ∧ same <= source.t ∧ interFree <= {n} - 2 * idx.k ∧",
        "    interFree <= row.val ∧ interFree <= col.val",
        "",
        f"instance {name_prefix}BlockCoeffSupportCondition_decidable",
        f"    (idx : BinaryBlockIndex {n})",
        "    (row col : BinaryBlockCoord idx)",
        f"    (source : BinaryOrbitIndex {n}) (same : Nat) :",
        f"    Decidable ({name_prefix}BlockCoeffSupportCondition",
        "      idx row col source same) := by",
        f"  unfold {name_prefix}BlockCoeffSupportCondition",
        "  infer_instance",
        "",
        f"def {name_prefix}BlockCoeffSupportChoices",
        f"    (idx : BinaryBlockIndex {n})",
        "    (row col : BinaryBlockCoord idx)",
        f"    (source : BinaryOrbitIndex {n}) (same : Nat) :",
        "    Finset ((Finset (Fin idx.k) × Finset (Fin idx.k)) ×",
        f"      Sigma (fun _I : Finset (Fin {n}) =>",
        f"        Sigma (fun _P : Finset (Fin {n}) => Finset (Fin {n})))) :=",
        "  let interFree := source.t - same",
        f"  if {name_prefix}BlockCoeffSupportCondition idx row col source same then",
        f"    ({name_prefix}PairPartChoices idx same).product",
        f"      ({name_prefix}FreePairChoices idx row.val col.val interFree)",
        "  else",
        "    ∅",
        "",
        f"def {name_prefix}BlockCoeffSignlessTerm",
        f"    (idx : BinaryBlockIndex {n})",
        "    (row col : BinaryBlockCoord idx)",
        f"    (source : BinaryOrbitIndex {n}) (same : Nat) : Nat :=",
        "  let interFree := source.t - same",
        f"  if {name_prefix}BlockCoeffSupportCondition idx row col source same then",
        "    2 ^ idx.k *",
        "      Nat.choose idx.k same *",
        f"      Nat.choose ({n} - 2 * idx.k) interFree *",
        f"      Nat.choose ({n} - 2 * idx.k - interFree) (row.val - interFree) *",
        f"      Nat.choose ({n} - 2 * idx.k - row.val) (col.val - interFree)",
        "  else",
        "    0",
        "",
        f"theorem {name_prefix}BlockCoeffSupportChoices_card",
        f"    (idx : BinaryBlockIndex {n})",
        "    (row col : BinaryBlockCoord idx)",
        f"    (source : BinaryOrbitIndex {n}) (same : Nat) :",
        f"    ({name_prefix}BlockCoeffSupportChoices idx row col source same).card =",
        f"      {name_prefix}BlockCoeffSignlessTerm idx row col source same := by",
        f"  unfold {name_prefix}BlockCoeffSupportChoices {name_prefix}BlockCoeffSignlessTerm",
        f"  by_cases hcond : {name_prefix}BlockCoeffSupportCondition idx row col source same",
        "  · simp [hcond]",
        f"    rw [{name_prefix}PairPartChoices_card]",
        f"    rw [{name_prefix}FreePairChoices_card]",
        "    · ring",
        f"    · unfold {name_prefix}BlockCoeffSupportCondition at hcond",
        "      exact hcond.2.2.2.2.2.1",
        "  · simp [hcond]",
        "",
        f"def {name_prefix}BlockCoeffSupportPairs",
        f"    (idx : BinaryBlockIndex {n})",
        "    (row col : BinaryBlockCoord idx)",
        f"    (source : BinaryOrbitIndex {n}) (same : Nat) :",
        f"    Finset (Finset (Fin {n}) × Finset (Fin {n})) :=",
        f"  ((Finset.univ : Finset (Finset (Fin {n}))).product",
        f"    (Finset.univ : Finset (Finset (Fin {n})))).filter (fun st =>",
        f"      {name_prefix}PairChoiceValid idx st.1 ∧",
        f"        {name_prefix}PairChoiceValid idx st.2 ∧",
        "        st.1.card = idx.k + row.val ∧",
        "        st.2.card = idx.k + col.val ∧",
        "        source = binaryOrbitOf",
        "          (binaryWordOfSupport st.1) (binaryWordOfSupport st.2) ∧",
        f"        ({name_prefix}PairSameChoices idx st.1 st.2).card = same)",
        "",
        f"def {name_prefix}BlockCoeffSupportPairBase",
        f"    (idx : BinaryBlockIndex {n})",
        "    (row col : BinaryBlockCoord idx)",
        f"    (source : BinaryOrbitIndex {n}) :",
        f"    Finset (Finset (Fin {n}) × Finset (Fin {n})) :=",
        f"  ((Finset.univ : Finset (Finset (Fin {n}))).product",
        f"    (Finset.univ : Finset (Finset (Fin {n})))).filter (fun st =>",
        f"      {name_prefix}PairChoiceValid idx st.1 ∧",
        f"        {name_prefix}PairChoiceValid idx st.2 ∧",
        "        st.1.card = idx.k + row.val ∧",
        "        st.2.card = idx.k + col.val ∧",
        "        source = binaryOrbitOf",
        "          (binaryWordOfSupport st.1) (binaryWordOfSupport st.2))",
        "",
        f"theorem {name_prefix}BlockCoeffSupportPairs_eq_base_filter",
        f"    (idx : BinaryBlockIndex {n})",
        "    (row col : BinaryBlockCoord idx)",
        f"    (source : BinaryOrbitIndex {n}) (same : Nat) :",
        f"    {name_prefix}BlockCoeffSupportPairs idx row col source same =",
        f"      ({name_prefix}BlockCoeffSupportPairBase idx row col source).filter (fun st =>",
        f"        ({name_prefix}PairSameChoices idx st.1 st.2).card = same) := by",
        "  ext st",
        f"  simp [{name_prefix}BlockCoeffSupportPairs,",
        f"    {name_prefix}BlockCoeffSupportPairBase, and_assoc]",
        "",
        f"theorem {name_prefix}BlockCoeffSupportPairBase_same_mem_range",
        f"    (idx : BinaryBlockIndex {n})",
        "    (row col : BinaryBlockCoord idx)",
        f"    (source : BinaryOrbitIndex {n})",
        f"    (st : Finset (Fin {n}) × Finset (Fin {n}))",
        f"    (_hst : st ∈ {name_prefix}BlockCoeffSupportPairBase idx row col source) :",
        f"    ({name_prefix}PairSameChoices idx st.1 st.2).card ∈",
        "      Finset.range (idx.k + 1) := by",
        "  have hsubset :",
        f"      {name_prefix}PairSameChoices idx st.1 st.2 ⊆",
        "        (Finset.univ : Finset (Fin idx.k)) := by",
        "    intro a _",
        "    simp",
        "  have hle := Finset.card_le_card hsubset",
        "  simp at hle",
        "  exact Finset.mem_range.mpr (Nat.lt_succ_of_le hle)",
        "",
        f"def {name_prefix}PairSupportFromRightChoices",
        f"    (idx : BinaryBlockIndex {n}) (rights : Finset (Fin idx.k)) :",
        f"    Finset (Fin {n}) :=",
        "  (Finset.univ : Finset (Fin idx.k)).image (fun a =>",
        "    if a ∈ rights then",
        f"      {name_prefix}PairRightCoord idx a",
        "    else",
        f"      {name_prefix}PairLeftCoord idx a)",
        "",
        f"def {name_prefix}PairSupportForT",
        f"    (idx : BinaryBlockIndex {n}) (same rights : Finset (Fin idx.k)) :",
        f"    Finset (Fin {n}) :=",
        "  (Finset.univ : Finset (Fin idx.k)).image (fun a =>",
        "    if (a ∈ same ∧ a ∈ rights) ∨ (a ∉ same ∧ a ∉ rights) then",
        f"      {name_prefix}PairRightCoord idx a",
        "    else",
        f"      {name_prefix}PairLeftCoord idx a)",
        "",
        f"theorem {name_prefix}PairSupportFromRightChoices_valid",
        f"    (idx : BinaryBlockIndex {n}) (rights : Finset (Fin idx.k)) :",
        f"    {name_prefix}PairChoiceValid idx",
        f"      ({name_prefix}PairSupportFromRightChoices idx rights) := by",
        "  rcases idx with ⟨k, hk⟩",
        "  have hk' : k ≤ 6 := by omega",
        "  interval_cases k <;> native_decide +revert",
        "",
        f"theorem {name_prefix}PairSupportForT_valid",
        f"    (idx : BinaryBlockIndex {n}) (same rights : Finset (Fin idx.k)) :",
        f"    {name_prefix}PairChoiceValid idx",
        f"      ({name_prefix}PairSupportForT idx same rights) := by",
        "  rcases idx with ⟨k, hk⟩",
        "  have hk' : k ≤ 6 := by omega",
        "  interval_cases k <;> native_decide +revert",
        "",
        f"theorem {name_prefix}PairSupportFromRightChoices_card",
        f"    (idx : BinaryBlockIndex {n}) (rights : Finset (Fin idx.k)) :",
        f"    ({name_prefix}PairSupportFromRightChoices idx rights).card = idx.k := by",
        "  rcases idx with ⟨k, hk⟩",
        "  have hk' : k ≤ 6 := by omega",
        "  interval_cases k <;> native_decide +revert",
        "",
        f"theorem {name_prefix}PairSupportForT_card",
        f"    (idx : BinaryBlockIndex {n}) (same rights : Finset (Fin idx.k)) :",
        f"    ({name_prefix}PairSupportForT idx same rights).card = idx.k := by",
        "  rcases idx with ⟨k, hk⟩",
        "  have hk' : k ≤ 6 := by omega",
        "  interval_cases k <;> native_decide +revert",
        "",
        f"theorem {name_prefix}PairSupport_same_choices",
        f"    (idx : BinaryBlockIndex {n}) (same rights : Finset (Fin idx.k)) :",
        f"    {name_prefix}PairSameChoices idx",
        f"      ({name_prefix}PairSupportFromRightChoices idx rights)",
        f"      ({name_prefix}PairSupportForT idx same rights) = same := by",
        "  rcases idx with ⟨k, hk⟩",
        "  have hk' : k ≤ 6 := by omega",
        "  interval_cases k <;> native_decide +revert",
        "",
        f"theorem {name_prefix}PairSupportFromRightChoices_disjoint_free",
        f"    (idx : BinaryBlockIndex {n}) (rights : Finset (Fin idx.k)) :",
        f"    Disjoint ({name_prefix}PairSupportFromRightChoices idx rights)",
        f"      ({name_prefix}BlockFreeCoords idx) := by",
        "  rcases idx with ⟨k, hk⟩",
        "  have hk' : k ≤ 6 := by omega",
        "  interval_cases k <;> native_decide +revert",
        "",
        f"theorem {name_prefix}PairSupportForT_disjoint_free",
        f"    (idx : BinaryBlockIndex {n}) (same rights : Finset (Fin idx.k)) :",
        f"    Disjoint ({name_prefix}PairSupportForT idx same rights)",
        f"      ({name_prefix}BlockFreeCoords idx) := by",
        "  rcases idx with ⟨k, hk⟩",
        "  have hk' : k ≤ 6 := by omega",
        "  interval_cases k <;> native_decide +revert",
        "",
        f"theorem {name_prefix}PairSupport_inter_card",
        f"    (idx : BinaryBlockIndex {n}) (same rights : Finset (Fin idx.k)) :",
        f"    ({name_prefix}PairSupportFromRightChoices idx rights ∩",
        f"        {name_prefix}PairSupportForT idx same rights).card = same.card := by",
        "  rcases idx with ⟨k, hk⟩",
        "  have hk' : k ≤ 6 := by omega",
        "  interval_cases k <;> native_decide +revert",
        "",
        f"theorem {name_prefix}PairLeftCoord_not_mem_free",
        f"    (idx : BinaryBlockIndex {n}) (a : Fin idx.k) :",
        f"    {name_prefix}PairLeftCoord idx a ∉",
        f"      {name_prefix}BlockFreeCoords idx := by",
        "  have ha := a.isLt",
        f"  simp [{name_prefix}BlockFreeCoords, {name_prefix}PairLeftCoord]",
        "  omega",
        "",
        f"theorem {name_prefix}PairRightCoord_not_mem_free",
        f"    (idx : BinaryBlockIndex {n}) (a : Fin idx.k) :",
        f"    {name_prefix}PairRightCoord idx a ∉",
        f"      {name_prefix}BlockFreeCoords idx := by",
        "  have ha := a.isLt",
        f"  simp [{name_prefix}BlockFreeCoords, {name_prefix}PairRightCoord]",
        "  omega",
        "",
        f"theorem {name_prefix}PairChoiceValid_union_free",
        f"    (idx : BinaryBlockIndex {n}) (S F : Finset (Fin {n}))",
        f"    (hvalid : {name_prefix}PairChoiceValid idx S)",
        f"    (hF : F ⊆ {name_prefix}BlockFreeCoords idx) :",
        f"    {name_prefix}PairChoiceValid idx (S ∪ F) := by",
        "  intro a",
        f"  have hleftF : {name_prefix}PairLeftCoord idx a ∉ F := by",
        "    intro h",
        f"    exact {name_prefix}PairLeftCoord_not_mem_free idx a (hF h)",
        f"  have hrightF : {name_prefix}PairRightCoord idx a ∉ F := by",
        "    intro h",
        f"    exact {name_prefix}PairRightCoord_not_mem_free idx a (hF h)",
        "  rcases hvalid a with hleft | hright",
        "  · exact Or.inl",
        "      ⟨Finset.mem_union.mpr (Or.inl hleft.1), by",
        "        intro hmem",
        "        rcases Finset.mem_union.mp hmem with hmem | hmem",
        "        · exact hleft.2 hmem",
        "        · exact hrightF hmem⟩",
        "  · exact Or.inr",
        "      ⟨by",
        "        intro hmem",
        "        rcases Finset.mem_union.mp hmem with hmem | hmem",
        "        · exact hright.1 hmem",
        "        · exact hleftF hmem,",
        "        Finset.mem_union.mpr (Or.inl hright.2)⟩",
        "",
        f"theorem {name_prefix}PairSupportFromRightChoices_union_free_card",
        f"    (idx : BinaryBlockIndex {n}) (rights : Finset (Fin idx.k))",
        f"    (F : Finset (Fin {n}))",
        f"    (hF : F ⊆ {name_prefix}BlockFreeCoords idx) :",
        f"    ({name_prefix}PairSupportFromRightChoices idx rights ∪ F).card =",
        "      idx.k + F.card := by",
        f"  have hdisj : Disjoint ({name_prefix}PairSupportFromRightChoices idx rights) F := by",
        "    rw [Finset.disjoint_left]",
        "    intro coord hpair hfree",
        "    exact (Finset.disjoint_left.mp",
        f"      ({name_prefix}PairSupportFromRightChoices_disjoint_free idx rights))",
        "      hpair (hF hfree)",
        "  rw [Finset.card_union_of_disjoint hdisj]",
        f"  rw [{name_prefix}PairSupportFromRightChoices_card]",
        "",
        f"theorem {name_prefix}PairSupportForT_union_free_card",
        f"    (idx : BinaryBlockIndex {n}) (same rights : Finset (Fin idx.k))",
        f"    (F : Finset (Fin {n}))",
        f"    (hF : F ⊆ {name_prefix}BlockFreeCoords idx) :",
        f"    ({name_prefix}PairSupportForT idx same rights ∪ F).card =",
        "      idx.k + F.card := by",
        f"  have hdisj : Disjoint ({name_prefix}PairSupportForT idx same rights) F := by",
        "    rw [Finset.disjoint_left]",
        "    intro coord hpair hfree",
        "    exact (Finset.disjoint_left.mp",
        f"      ({name_prefix}PairSupportForT_disjoint_free idx same rights))",
        "      hpair (hF hfree)",
        "  rw [Finset.card_union_of_disjoint hdisj]",
        f"  rw [{name_prefix}PairSupportForT_card]",
        "",
        "/--",
        "One signed pair factor in the concrete length-13 Schrijver compression",
        "matrix.  For pair `(a,k+a)`, the value is `1` on `(1,0)`, `-1` on",
        "`(0,1)`, and `0` otherwise.",
        "-/",
        f"def {name_prefix}PairSign",
        f"    (w : QaryWord 2 {n}) (k a : Nat) : Rat :=",
        f"  if hleft : a < {n} then",
        f"    if hright : k + a < {n} then",
        "      if w ⟨a, hleft⟩ = 1 ∧ w ⟨k + a, hright⟩ = 0 then 1",
        "      else if w ⟨a, hleft⟩ = 0 ∧ w ⟨k + a, hright⟩ = 1 then -1",
        "      else 0",
        "    else 0",
        "  else 0",
        "",
        f"theorem {name_prefix}PairSign_wordOfSupport",
        f"    (S : Finset (Fin {n})) {{k a : Nat}}",
        f"    (hleft : a < {n}) (hright : k + a < {n}) :",
        f"    {name_prefix}PairSign (binaryWordOfSupport S) k a =",
        f"      if (⟨a, hleft⟩ : Fin {n}) ∈ S ∧",
        f"          (⟨k + a, hright⟩ : Fin {n}) ∉ S then",
        "        1",
        f"      else if (⟨a, hleft⟩ : Fin {n}) ∉ S ∧",
        f"          (⟨k + a, hright⟩ : Fin {n}) ∈ S then",
        "        -1",
        "      else",
        "        0 := by",
        f"  unfold {name_prefix}PairSign",
        "  rw [dif_pos hleft, dif_pos hright]",
        "  simp [binaryWordOfSupport]",
        "",
        f"theorem {name_prefix}PairSign_wordOfSupport_fin",
        f"    (idx : BinaryBlockIndex {n})",
        f"    (S : Finset (Fin {n})) (a : Fin idx.k) :",
        f"    {name_prefix}PairSign (binaryWordOfSupport S) idx.k a.val =",
        f"      if {name_prefix}PairLeftCoord idx a ∈ S ∧",
        f"          {name_prefix}PairRightCoord idx a ∉ S then",
        "        1",
        f"      else if {name_prefix}PairLeftCoord idx a ∉ S ∧",
        f"          {name_prefix}PairRightCoord idx a ∈ S then",
        "        -1",
        "      else",
        "        0 := by",
        f"  have hleft : a.val < {n} := by",
        "    have ha := a.isLt",
        "    have hk := idx.hk",
        "    omega",
        f"  have hright : idx.k + a.val < {n} := by",
        "    have ha := a.isLt",
        "    have hk := idx.hk",
        "    omega",
        f"  simpa [{name_prefix}PairLeftCoord, {name_prefix}PairRightCoord] using",
        f"    ({name_prefix}PairSign_wordOfSupport S hleft hright)",
        "",
        f"theorem {name_prefix}PairSign_prod_eq_fin_prod",
        f"    (idx : BinaryBlockIndex {n}) (S : Finset (Fin {n})) :",
        "    (Finset.range idx.k).prod",
        f"        (fun a => {name_prefix}PairSign (binaryWordOfSupport S) idx.k a) =",
        "      (Finset.univ : Finset (Fin idx.k)).prod",
        f"        (fun a => {name_prefix}PairSign",
        "          (binaryWordOfSupport S) idx.k a.val) := by",
        "  simpa using",
        "    (Fin.prod_univ_eq_prod_range",
        f"      (fun a => {name_prefix}PairSign (binaryWordOfSupport S) idx.k a)",
        "      idx.k).symm",
        "",
        f"theorem {name_prefix}PairSign_prod_wordOfSupport_eq_fin_prod",
        f"    (idx : BinaryBlockIndex {n}) (S : Finset (Fin {n})) :",
        "    (Finset.range idx.k).prod",
        f"        (fun a => {name_prefix}PairSign (binaryWordOfSupport S) idx.k a) =",
        "      (Finset.univ : Finset (Fin idx.k)).prod",
        "        (fun a =>",
        f"          if {name_prefix}PairLeftCoord idx a ∈ S ∧",
        f"              {name_prefix}PairRightCoord idx a ∉ S then",
        "            (1 : Rat)",
        f"          else if {name_prefix}PairLeftCoord idx a ∉ S ∧",
        f"              {name_prefix}PairRightCoord idx a ∈ S then",
        "            -1",
        "          else",
        "            0) := by",
        f"  rw [{name_prefix}PairSign_prod_eq_fin_prod]",
        "  apply Finset.prod_congr rfl",
        "  intro a _",
        f"  rw [{name_prefix}PairSign_wordOfSupport_fin]",
        "",
        f"theorem {name_prefix}PairSign_wordOfSupport_fin_eq_if_right_of_valid",
        f"    (idx : BinaryBlockIndex {n}) (S : Finset (Fin {n}))",
        f"    (hvalid : {name_prefix}PairChoiceValid idx S)",
        "    (a : Fin idx.k) :",
        f"    {name_prefix}PairSign (binaryWordOfSupport S) idx.k a.val =",
        f"      if a ∈ {name_prefix}PairRightChoices idx S then (-1 : Rat) else 1 := by",
        f"  rw [{name_prefix}PairSign_wordOfSupport_fin]",
        f"  unfold {name_prefix}PairRightChoices",
        "  simp only [Finset.mem_filter, Finset.mem_univ, true_and]",
        "  rcases hvalid a with hleft | hright",
        "  · simp [hleft.1, hleft.2]",
        "  · simp [hright.1, hright.2]",
        "",
        f"theorem {name_prefix}PairSign_prod_wordOfSupport_eq_neg_one_pow_right_of_valid",
        f"    (idx : BinaryBlockIndex {n}) (S : Finset (Fin {n}))",
        f"    (hvalid : {name_prefix}PairChoiceValid idx S) :",
        "    (Finset.range idx.k).prod",
        f"        (fun a => {name_prefix}PairSign (binaryWordOfSupport S) idx.k a) =",
        f"      (-1 : Rat) ^ ({name_prefix}PairRightChoices idx S).card := by",
        f"  rw [{name_prefix}PairSign_prod_eq_fin_prod]",
        "  calc",
        "    (Finset.univ : Finset (Fin idx.k)).prod",
        f"        (fun a => {name_prefix}PairSign",
        "          (binaryWordOfSupport S) idx.k a.val) =",
        "        ∏ a : Fin idx.k,",
        f"          if a ∈ {name_prefix}PairRightChoices idx S then",
        "            (-1 : Rat)",
        "          else",
        "            1 := by",
        "          apply Finset.prod_congr rfl",
        "          intro a _",
        f"          exact {name_prefix}PairSign_wordOfSupport_fin_eq_if_right_of_valid",
        "            idx S hvalid a",
        f"    _ = ∏ a ∈ {name_prefix}PairRightChoices idx S, (-1 : Rat) := by",
        "          rw [Finset.prod_ite_mem_eq]",
        f"    _ = (-1 : Rat) ^ ({name_prefix}PairRightChoices idx S).card := by",
        "          rw [Finset.prod_eq_pow_card]",
        "          intro a _",
        "          rfl",
        "",
        f"theorem {name_prefix}PairSame_or_opposite_of_valid",
        f"    (idx : BinaryBlockIndex {n})",
        f"    (S T : Finset (Fin {n}))",
        f"    (hS : {name_prefix}PairChoiceValid idx S)",
        f"    (hT : {name_prefix}PairChoiceValid idx T)",
        "    (a : Fin idx.k) :",
        f"    a ∈ {name_prefix}PairSameChoices idx S T ∨",
        f"      a ∈ {name_prefix}PairOppositeChoices idx S T := by",
        f"  unfold {name_prefix}PairSameChoices {name_prefix}PairOppositeChoices",
        "  simp only [Finset.mem_filter, Finset.mem_univ, true_and]",
        "  rcases hS a with hSL | hSR",
        "  · rcases hT a with hTL | hTR",
        "    · exact Or.inl (Or.inl ⟨hSL.1, hTL.1⟩)",
        "    · exact Or.inr (Or.inl ⟨hSL.1, hTR.2⟩)",
        "  · rcases hT a with hTL | hTR",
        "    · exact Or.inr (Or.inr ⟨hSR.2, hTL.1⟩)",
        "    · exact Or.inl (Or.inr ⟨hSR.2, hTR.2⟩)",
        "",
        f"theorem {name_prefix}PairSame_disjoint_opposite",
        f"    (idx : BinaryBlockIndex {n})",
        f"    (S T : Finset (Fin {n}))",
        f"    (hS : {name_prefix}PairChoiceValid idx S)",
        f"    (hT : {name_prefix}PairChoiceValid idx T) :",
        f"    Disjoint ({name_prefix}PairSameChoices idx S T)",
        f"      ({name_prefix}PairOppositeChoices idx S T) := by",
        "  rw [Finset.disjoint_left]",
        "  intro a hsame hopp",
        f"  unfold {name_prefix}PairSameChoices at hsame",
        f"  unfold {name_prefix}PairOppositeChoices at hopp",
        "  simp only [Finset.mem_filter, Finset.mem_univ, true_and] at hsame hopp",
        "  rcases hsame with hLL | hRR",
        "  · rcases hopp with hLR | hRL",
        "    · rcases hT a with hTL | hTR",
        "      · exact hTL.2 hLR.2",
        "      · exact hTR.1 hLL.2",
        "    · rcases hS a with hSL | hSR",
        "      · exact hSL.2 hRL.1",
        "      · exact hSR.1 hLL.1",
        "  · rcases hopp with hLR | hRL",
        "    · rcases hS a with hSL | hSR",
        "      · exact hSL.2 hRR.1",
        "      · exact hSR.1 hLR.1",
        "    · rcases hT a with hTL | hTR",
        "      · exact hTL.2 hRR.2",
        "      · exact hTR.1 hRL.2",
        "",
        f"theorem {name_prefix}PairSame_union_opposite_of_valid",
        f"    (idx : BinaryBlockIndex {n})",
        f"    (S T : Finset (Fin {n}))",
        f"    (hS : {name_prefix}PairChoiceValid idx S)",
        f"    (hT : {name_prefix}PairChoiceValid idx T) :",
        f"    {name_prefix}PairSameChoices idx S T ∪",
        f"        {name_prefix}PairOppositeChoices idx S T =",
        "      Finset.univ := by",
        "  ext a",
        "  constructor",
        "  · intro _",
        "    simp",
        "  · intro _",
        "    exact Finset.mem_union.mpr",
        f"      ({name_prefix}PairSame_or_opposite_of_valid idx S T hS hT a)",
        "",
        f"theorem {name_prefix}PairOppositeChoices_card_of_valid",
        f"    (idx : BinaryBlockIndex {n})",
        f"    (S T : Finset (Fin {n}))",
        f"    (hS : {name_prefix}PairChoiceValid idx S)",
        f"    (hT : {name_prefix}PairChoiceValid idx T) :",
        f"    ({name_prefix}PairOppositeChoices idx S T).card =",
        f"      idx.k - ({name_prefix}PairSameChoices idx S T).card := by",
        f"  have hunion := {name_prefix}PairSame_union_opposite_of_valid idx S T hS hT",
        f"  have hdisj := {name_prefix}PairSame_disjoint_opposite idx S T hS hT",
        "  have hcard := congrArg Finset.card hunion",
        "  rw [Finset.card_union_of_disjoint hdisj] at hcard",
        "  simp at hcard",
        "  omega",
        "",
        f"theorem {name_prefix}PairSign_mul_eq_same_indicator_of_valid",
        f"    (idx : BinaryBlockIndex {n})",
        f"    (S T : Finset (Fin {n}))",
        f"    (hS : {name_prefix}PairChoiceValid idx S)",
        f"    (hT : {name_prefix}PairChoiceValid idx T)",
        "    (a : Fin idx.k) :",
        f"    {name_prefix}PairSign (binaryWordOfSupport S) idx.k a.val *",
        f"        {name_prefix}PairSign (binaryWordOfSupport T) idx.k a.val =",
        f"      if a ∈ {name_prefix}PairSameChoices idx S T then",
        "        (1 : Rat)",
        "      else",
        "        -1 := by",
        f"  rw [{name_prefix}PairSign_wordOfSupport_fin]",
        f"  rw [{name_prefix}PairSign_wordOfSupport_fin]",
        f"  unfold {name_prefix}PairSameChoices",
        "  simp only [Finset.mem_filter, Finset.mem_univ, true_and]",
        "  rcases hS a with hSL | hSR",
        "  · rcases hT a with hTL | hTR",
        "    · simp [hSL.1, hSL.2, hTL.1, hTL.2]",
        "    · simp [hSL.1, hSL.2, hTR.1, hTR.2]",
        "  · rcases hT a with hTL | hTR",
        "    · simp [hSR.1, hSR.2, hTL.1, hTL.2]",
        "    · simp [hSR.1, hSR.2, hTR.1, hTR.2]",
        "",
        f"theorem {name_prefix}PairSign_prod_mul_eq_neg_one_pow_opposite_of_valid",
        f"    (idx : BinaryBlockIndex {n})",
        f"    (S T : Finset (Fin {n}))",
        f"    (hS : {name_prefix}PairChoiceValid idx S)",
        f"    (hT : {name_prefix}PairChoiceValid idx T) :",
        "    (Finset.range idx.k).prod",
        f"        (fun a => {name_prefix}PairSign (binaryWordOfSupport S) idx.k a) *",
        "      (Finset.range idx.k).prod",
        f"        (fun a => {name_prefix}PairSign (binaryWordOfSupport T) idx.k a) =",
        f"      (-1 : Rat) ^ (idx.k - ({name_prefix}PairSameChoices idx S T).card) := by",
        f"  rw [{name_prefix}PairSign_prod_eq_fin_prod]",
        f"  rw [{name_prefix}PairSign_prod_eq_fin_prod]",
        "  rw [← Finset.prod_mul_distrib]",
        "  calc",
        "    (Finset.univ : Finset (Fin idx.k)).prod",
        f"        (fun x => {name_prefix}PairSign",
        "          (binaryWordOfSupport S) idx.k x.val *",
        f"            {name_prefix}PairSign",
        "              (binaryWordOfSupport T) idx.k x.val) =",
        "        ∏ a : Fin idx.k,",
        f"          if a ∈ {name_prefix}PairOppositeChoices idx S T then",
        "            (-1 : Rat)",
        "          else",
        "            1 := by",
        "          apply Finset.prod_congr rfl",
        "          intro a _",
        f"          have hmul := {name_prefix}PairSign_mul_eq_same_indicator_of_valid",
        "            idx S T hS hT a",
        f"          have hcover := {name_prefix}PairSame_or_opposite_of_valid idx S T hS hT a",
        f"          have hdisj := {name_prefix}PairSame_disjoint_opposite idx S T hS hT",
        f"          by_cases hsame : a ∈ {name_prefix}PairSameChoices idx S T",
        f"          · have hnopp : a ∉ {name_prefix}PairOppositeChoices idx S T := by",
        "              intro hopp",
        "              exact (Finset.disjoint_left.mp hdisj) hsame hopp",
        "            simp [hmul, hsame, hnopp]",
        f"          · have hopp : a ∈ {name_prefix}PairOppositeChoices idx S T := by",
        "              rcases hcover with hcover | hcover",
        "              · exact False.elim (hsame hcover)",
        "              · exact hcover",
        "            simp [hmul, hsame, hopp]",
        f"    _ = ∏ a ∈ {name_prefix}PairOppositeChoices idx S T, (-1 : Rat) := by",
        "          rw [Finset.prod_ite_mem_eq]",
        f"    _ = (-1 : Rat) ^ ({name_prefix}PairOppositeChoices idx S T).card := by",
        "          rw [Finset.prod_eq_pow_card]",
        "          intro a _",
        "          rfl",
        f"    _ = (-1 : Rat) ^ (idx.k -",
        f"        ({name_prefix}PairSameChoices idx S T).card) := by",
        f"          rw [{name_prefix}PairOppositeChoices_card_of_valid idx S T hS hT]",
        "",
        f"theorem {name_prefix}PairSign_wordOfSupport_fin_eq_zero_of_not_choice",
        f"    (idx : BinaryBlockIndex {n})",
        f"    (S : Finset (Fin {n})) (a : Fin idx.k)",
        "    (hnot :",
        f"      ¬ (({name_prefix}PairLeftCoord idx a ∈ S ∧",
        f"            {name_prefix}PairRightCoord idx a ∉ S) ∨",
        f"          ({name_prefix}PairLeftCoord idx a ∉ S ∧",
        f"            {name_prefix}PairRightCoord idx a ∈ S))) :",
        f"    {name_prefix}PairSign (binaryWordOfSupport S) idx.k a.val = 0 := by",
        f"  rw [{name_prefix}PairSign_wordOfSupport_fin]",
        f"  by_cases hleft : {name_prefix}PairLeftCoord idx a ∈ S ∧",
        f"      {name_prefix}PairRightCoord idx a ∉ S",
        "  · exact False.elim (hnot (Or.inl hleft))",
        f"  · by_cases hright : {name_prefix}PairLeftCoord idx a ∉ S ∧",
        f"        {name_prefix}PairRightCoord idx a ∈ S",
        "    · exact False.elim (hnot (Or.inr hright))",
        "    · simp [hleft, hright]",
        "",
        f"theorem {name_prefix}PairSign_prod_wordOfSupport_eq_zero_of_not_valid",
        f"    (idx : BinaryBlockIndex {n}) (S : Finset (Fin {n}))",
        f"    (hnot : ¬ {name_prefix}PairChoiceValid idx S) :",
        "    (Finset.range idx.k).prod",
        f"        (fun a => {name_prefix}PairSign (binaryWordOfSupport S) idx.k a) =",
        "      0 := by",
        f"  rw [{name_prefix}PairSign_prod_eq_fin_prod]",
        f"  unfold {name_prefix}PairChoiceValid at hnot",
        "  push Not at hnot",
        "  rcases hnot with ⟨a, ha⟩",
        "  have hnotChoice :",
        f"      ¬ (({name_prefix}PairLeftCoord idx a ∈ S ∧",
        f"            {name_prefix}PairRightCoord idx a ∉ S) ∨",
        f"          ({name_prefix}PairLeftCoord idx a ∉ S ∧",
        f"            {name_prefix}PairRightCoord idx a ∈ S)) := by",
        "    intro hchoice",
        "    rcases hchoice with hleft | hright",
        "    · exact hleft.2 (ha.1 hleft.1)",
        "    · exact (ha.2 hright.1) hright.2",
        "  exact Finset.prod_eq_zero (Finset.mem_univ a)",
        f"    ({name_prefix}PairSign_wordOfSupport_fin_eq_zero_of_not_choice",
        "      idx S a hnotChoice)",
        "",
        "/--",
        "Concrete signed compression matrix from binary words to the dependent",
        "Schrijver block-coordinate space.  For a block coordinate `(k,row)`,",
        "the row represents shell `k + row`; outside that shell the entry is zero.",
        "-/",
        f"def {name_prefix}BlockCompressionMatrix :",
        f"    Matrix (QaryWord 2 {n})",
        f"      (Sigma (fun idx : BinaryBlockIndex {n} => BinaryBlockCoord idx)) Rat :=",
        "  fun w p =>",
        f"    if (binarySupport {n} w).card = p.1.k + p.2.val then",
        "      (Finset.range p.1.k).prod",
        f"        (fun a => {name_prefix}PairSign w p.1.k a)",
        "    else 0",
        "",
        "/-- Single-block version of the length-13 compression matrix. -/",
        f"def {name_prefix}BlockCompressionMatrixFor",
        f"    (idx : BinaryBlockIndex {n}) :",
        f"    Matrix (QaryWord 2 {n}) (BinaryBlockCoord idx) Rat :=",
        "  fun w coord =>",
        f"    if (binarySupport {n} w).card = idx.k + coord.val then",
        "      (Finset.range idx.k).prod",
        f"        (fun a => {name_prefix}PairSign w idx.k a)",
        "    else 0",
        "",
        f"theorem {name_prefix}BlockCompressionMatrixFor_apply",
        f"    (idx : BinaryBlockIndex {n}) (w : QaryWord 2 {n})",
        "    (coord : BinaryBlockCoord idx) :",
        f"    {name_prefix}BlockCompressionMatrixFor idx w coord =",
        f"      {name_prefix}BlockCompressionMatrix w ⟨idx, coord⟩ := by",
        f"  rfl",
        "",
        f"theorem {name_prefix}BlockCompressionMatrixFor_wordOfSupport",
        f"    (idx : BinaryBlockIndex {n}) (S : Finset (Fin {n}))",
        "    (coord : BinaryBlockCoord idx) :",
        f"    {name_prefix}BlockCompressionMatrixFor idx",
        "        (binaryWordOfSupport S) coord =",
        "      if S.card = idx.k + coord.val then",
        "        (Finset.range idx.k).prod",
        f"          (fun a => {name_prefix}PairSign",
        "            (binaryWordOfSupport S) idx.k a)",
        "      else",
        "        0 := by",
        f"  simp [{name_prefix}BlockCompressionMatrixFor]",
        "",
        f"theorem {name_prefix}BlockCompressionMatrixFor_wordOfSupport_eq_of_valid_card",
        f"    (idx : BinaryBlockIndex {n}) (S : Finset (Fin {n}))",
        "    (coord : BinaryBlockCoord idx)",
        f"    (hvalid : {name_prefix}PairChoiceValid idx S)",
        "    (hcard : S.card = idx.k + coord.val) :",
        f"    {name_prefix}BlockCompressionMatrixFor idx",
        "        (binaryWordOfSupport S) coord =",
        f"      (-1 : Rat) ^ ({name_prefix}PairRightChoices idx S).card := by",
        f"  rw [{name_prefix}BlockCompressionMatrixFor_wordOfSupport]",
        "  simp [hcard,",
        f"    {name_prefix}PairSign_prod_wordOfSupport_eq_neg_one_pow_right_of_valid",
        "      idx S hvalid]",
        "",
        f"theorem {name_prefix}BlockCompressionMatrixFor_wordOfSupport_eq_zero_of_not_valid",
        f"    (idx : BinaryBlockIndex {n}) (S : Finset (Fin {n}))",
        "    (coord : BinaryBlockCoord idx)",
        f"    (hnot : ¬ {name_prefix}PairChoiceValid idx S) :",
        f"    {name_prefix}BlockCompressionMatrixFor idx",
        "        (binaryWordOfSupport S) coord = 0 := by",
        f"  rw [{name_prefix}BlockCompressionMatrixFor_wordOfSupport]",
        f"  have hprod := {name_prefix}PairSign_prod_wordOfSupport_eq_zero_of_not_valid",
        "    idx S hnot",
        "  by_cases hcard : S.card = idx.k + coord.val <;> simp [hcard, hprod]",
        "",
        f"theorem {name_prefix}BlockCompressionMatrixFor_wordOfSupport_eq_zero_of_card_ne",
        f"    (idx : BinaryBlockIndex {n}) (S : Finset (Fin {n}))",
        "    (coord : BinaryBlockCoord idx)",
        "    (hcard : S.card ≠ idx.k + coord.val) :",
        f"    {name_prefix}BlockCompressionMatrixFor idx",
        "        (binaryWordOfSupport S) coord = 0 := by",
        f"  rw [{name_prefix}BlockCompressionMatrixFor_wordOfSupport]",
        "  simp [hcard]",
        "",
        "/--",
        "Actual linear-expression entry produced by the word-space congruence",
        "`T^T A T` for one length-13 block.",
        "-/",
        f"def {name_prefix}BlockCompressionEntryExpr",
        f"    (idx : BinaryBlockIndex {n})",
        "    (row col : BinaryBlockCoord idx) :",
        f"    LinExpr (BinaryOrbitIndex {n}) :=",
        "  LinExpr.sum Finset.univ (fun u =>",
        "    LinExpr.sum Finset.univ (fun v =>",
        f"      LinExpr.smul",
        f"        ({name_prefix}BlockCompressionMatrixFor idx u row *",
        f"          {name_prefix}BlockCompressionMatrixFor idx v col)",
        "        (LinExpr.var (binaryOrbitOf u v))))",
        "",
        f"theorem {name_prefix}BlockCompressionEntryExpr_eval",
        f"    (idx : BinaryBlockIndex {n})",
        "    (row col : BinaryBlockCoord idx)",
        f"    (x : BinaryOrbitIndex {n} -> Rat) :",
        f"    ({name_prefix}BlockCompressionEntryExpr idx row col).eval x =",
        "      congruenceMatrix",
        f"        ({name_prefix}BlockCompressionMatrixFor idx)",
        "        (binaryTerwilligerMatrix x) row col := by",
        f"  unfold {name_prefix}BlockCompressionEntryExpr congruenceMatrix",
        "    binaryTerwilligerMatrix",
        "  simp only [LinExpr.eval_sum, LinExpr.eval_smul, LinExpr.eval_var]",
        "  apply Finset.sum_congr rfl",
        "  intro u _",
        "  apply Finset.sum_congr rfl",
        "  intro v _",
        "  ring",
        "",
        f"theorem {name_prefix}BlockCompressionEntryExpr_coeff_sum",
        f"    (idx : BinaryBlockIndex {n})",
        "    (row col : BinaryBlockCoord idx)",
        f"    (source : BinaryOrbitIndex {n}) :",
        f"    ({name_prefix}BlockCompressionEntryExpr idx row col).coeff source =",
        f"      Finset.univ.sum (fun u : QaryWord 2 {n} =>",
        f"        Finset.univ.sum (fun v : QaryWord 2 {n} =>",
        f"          {name_prefix}BlockCompressionMatrixFor idx u row *",
        f"            {name_prefix}BlockCompressionMatrixFor idx v col *",
        "              (if source = binaryOrbitOf u v then (1 : Rat) else 0))) := by",
        f"  unfold {name_prefix}BlockCompressionEntryExpr",
        "  simp only [LinExpr.sum]",
        "  apply Finset.sum_congr rfl",
        "  intro u _",
        "  apply Finset.sum_congr rfl",
        "  intro v _",
        "  simp [LinExpr.smul, LinExpr.var]",
        "",
        f"theorem {name_prefix}BlockCompressionEntryExpr_coeff_support_sum",
        f"    (idx : BinaryBlockIndex {n})",
        "    (row col : BinaryBlockCoord idx)",
        f"    (source : BinaryOrbitIndex {n}) :",
        f"    ({name_prefix}BlockCompressionEntryExpr idx row col).coeff source =",
        f"      Finset.univ.sum (fun S : Finset (Fin {n}) =>",
        f"        Finset.univ.sum (fun T : Finset (Fin {n}) =>",
        f"          {name_prefix}BlockCompressionMatrixFor idx",
        "              (binaryWordOfSupport S) row *",
        f"            {name_prefix}BlockCompressionMatrixFor idx",
        "              (binaryWordOfSupport T) col *",
        "              (if source = binaryOrbitOf",
        "                  (binaryWordOfSupport S) (binaryWordOfSupport T) then",
        "                (1 : Rat)",
        "              else 0))) := by",
        f"  rw [{name_prefix}BlockCompressionEntryExpr_coeff_sum]",
        f"  rw [binary_sum_support (n := {n})",
        f"    (f := fun u : QaryWord 2 {n} =>",
        f"      Finset.univ.sum (fun v : QaryWord 2 {n} =>",
        f"        {name_prefix}BlockCompressionMatrixFor idx u row *",
        f"          {name_prefix}BlockCompressionMatrixFor idx v col *",
        "            (if source = binaryOrbitOf u v then (1 : Rat) else 0)))]",
        "  apply Finset.sum_congr rfl",
        "  intro S _",
        f"  rw [binary_sum_support (n := {n})",
        f"    (f := fun v : QaryWord 2 {n} =>",
        f"      {name_prefix}BlockCompressionMatrixFor idx",
        "          (binaryWordOfSupport S) row *",
        f"        {name_prefix}BlockCompressionMatrixFor idx v col *",
        "          (if source = binaryOrbitOf (binaryWordOfSupport S) v then",
        "            (1 : Rat)",
        "          else 0))]",
        "",
        f"theorem {name_prefix}BlockCompressionEntryExpr_coeff_support_matrix_expanded",
        f"    (idx : BinaryBlockIndex {n})",
        "    (row col : BinaryBlockCoord idx)",
        f"    (source : BinaryOrbitIndex {n}) :",
        f"    ({name_prefix}BlockCompressionEntryExpr idx row col).coeff source =",
        f"      Finset.univ.sum (fun S : Finset (Fin {n}) =>",
        f"        Finset.univ.sum (fun T : Finset (Fin {n}) =>",
        "          (if S.card = idx.k + row.val then",
        "            (Finset.range idx.k).prod",
        f"              (fun a => {name_prefix}PairSign",
        "                (binaryWordOfSupport S) idx.k a)",
        "          else",
        "            0) *",
        "          (if T.card = idx.k + col.val then",
        "            (Finset.range idx.k).prod",
        f"              (fun a => {name_prefix}PairSign",
        "                (binaryWordOfSupport T) idx.k a)",
        "          else",
        "            0) *",
        "          (if source = binaryOrbitOf",
        "              (binaryWordOfSupport S) (binaryWordOfSupport T) then",
        "            (1 : Rat)",
        "          else",
        "            0))) := by",
        f"  rw [{name_prefix}BlockCompressionEntryExpr_coeff_support_sum]",
        "  apply Finset.sum_congr rfl",
        "  intro S _",
        "  apply Finset.sum_congr rfl",
        "  intro T _",
        f"  rw [{name_prefix}BlockCompressionMatrixFor_wordOfSupport]",
        f"  rw [{name_prefix}BlockCompressionMatrixFor_wordOfSupport]",
        "",
        f"theorem {name_prefix}BlockCompressionEntryExpr_coeff_support_pair_indicator",
        f"    (idx : BinaryBlockIndex {n})",
        "    (row col : BinaryBlockCoord idx)",
        f"    (source : BinaryOrbitIndex {n}) :",
        f"    ({name_prefix}BlockCompressionEntryExpr idx row col).coeff source =",
        f"      Finset.univ.sum (fun S : Finset (Fin {n}) =>",
        f"        Finset.univ.sum (fun T : Finset (Fin {n}) =>",
        f"          if {name_prefix}PairChoiceValid idx S ∧",
        f"              {name_prefix}PairChoiceValid idx T ∧",
        "              S.card = idx.k + row.val ∧",
        "              T.card = idx.k + col.val ∧",
        "              source = binaryOrbitOf",
        "                (binaryWordOfSupport S) (binaryWordOfSupport T) then",
        "            (-1 : Rat) ^",
        f"              (idx.k - ({name_prefix}PairSameChoices idx S T).card)",
        "          else",
        "            0)) := by",
        f"  rw [{name_prefix}BlockCompressionEntryExpr_coeff_support_matrix_expanded]",
        "  apply Finset.sum_congr rfl",
        "  intro S _",
        "  apply Finset.sum_congr rfl",
        "  intro T _",
        f"  by_cases hSvalid : {name_prefix}PairChoiceValid idx S",
        f"  · by_cases hTvalid : {name_prefix}PairChoiceValid idx T",
        "    · by_cases hScard : S.card = idx.k + row.val",
        "      · by_cases hTcard : T.card = idx.k + col.val",
        "        · by_cases horbit :",
        "              source = binaryOrbitOf",
        "                (binaryWordOfSupport S) (binaryWordOfSupport T)",
        "          · simp [hSvalid, hTvalid, hScard, hTcard, horbit,",
        f"              {name_prefix}PairSign_prod_mul_eq_neg_one_pow_opposite_of_valid",
        "                idx S T hSvalid hTvalid]",
        "          · simp [hSvalid, hTvalid, hScard, hTcard, horbit]",
        "        · simp [hSvalid, hTvalid, hScard, hTcard]",
        "      · simp [hSvalid, hTvalid, hScard]",
        "    · have hTprod :=",
        f"        {name_prefix}PairSign_prod_wordOfSupport_eq_zero_of_not_valid",
        "          idx T hTvalid",
        "      simp [hSvalid, hTvalid, hTprod]",
        "  · have hSprod :=",
        f"      {name_prefix}PairSign_prod_wordOfSupport_eq_zero_of_not_valid",
        "        idx S hSvalid",
        "    simp [hSvalid, hSprod]",
        "",
        f"theorem {name_prefix}BlockCompressionEntryExpr_coeff_supportPairs_sum",
        f"    (idx : BinaryBlockIndex {n})",
        "    (row col : BinaryBlockCoord idx)",
        f"    (source : BinaryOrbitIndex {n}) :",
        f"    ({name_prefix}BlockCompressionEntryExpr idx row col).coeff source =",
        "      (Finset.range (idx.k + 1)).sum (fun same =>",
        "        (-1 : Rat) ^ (idx.k - same) *",
        f"          (({name_prefix}BlockCoeffSupportPairs idx row col source same).card : Rat)) := by",
        f"  rw [{name_prefix}BlockCompressionEntryExpr_coeff_support_pair_indicator]",
        f"  let base := {name_prefix}BlockCoeffSupportPairBase idx row col source",
        f"  let classOf : Finset (Fin {n}) × Finset (Fin {n}) -> Nat :=",
        f"    fun st => ({name_prefix}PairSameChoices idx st.1 st.2).card",
        "  have hmaps :",
        f"      (base : Set (Finset (Fin {n}) × Finset (Fin {n}))).MapsTo classOf",
        "        ((Finset.range (idx.k + 1)) : Set Nat) := by",
        "    intro st _hst",
        "    have hsubset :",
        f"        {name_prefix}PairSameChoices idx st.1 st.2 ⊆",
        "          (Finset.univ : Finset (Fin idx.k)) := by",
        "      intro a _",
        "      simp",
        "    have hle := Finset.card_le_card hsubset",
        "    simp at hle",
        "    exact Finset.mem_range.mpr (Nat.lt_succ_of_le hle)",
        "  calc",
        f"    (Finset.univ.sum (fun S : Finset (Fin {n}) =>",
        f"        Finset.univ.sum (fun T : Finset (Fin {n}) =>",
        f"          if {name_prefix}PairChoiceValid idx S ∧",
        f"              {name_prefix}PairChoiceValid idx T ∧",
        "              S.card = idx.k + row.val ∧",
        "              T.card = idx.k + col.val ∧",
        "              source = binaryOrbitOf",
        "                (binaryWordOfSupport S) (binaryWordOfSupport T) then",
        "            (-1 : Rat) ^",
        f"              (idx.k - ({name_prefix}PairSameChoices idx S T).card)",
        "          else",
        "            0))) =",
        "        (∑ st ∈ base, (-1 : Rat) ^ (idx.k - classOf st)) := by",
        "          change",
        f"            (Finset.univ.sum (fun S : Finset (Fin {n}) =>",
        f"              Finset.univ.sum (fun T : Finset (Fin {n}) =>",
        f"                if {name_prefix}PairChoiceValid idx S ∧",
        f"                    {name_prefix}PairChoiceValid idx T ∧",
        "                    S.card = idx.k + row.val ∧",
        "                    T.card = idx.k + col.val ∧",
        "                    source = binaryOrbitOf",
        "                      (binaryWordOfSupport S) (binaryWordOfSupport T) then",
        "                  (-1 : Rat) ^",
        f"                    (idx.k - ({name_prefix}PairSameChoices idx S T).card)",
        "                else",
        "                  0))) =",
        f"              ((((Finset.univ : Finset (Finset (Fin {n}))).product",
        f"                (Finset.univ : Finset (Finset (Fin {n})))).filter (fun st =>",
        f"                  {name_prefix}PairChoiceValid idx st.1 ∧",
        f"                    {name_prefix}PairChoiceValid idx st.2 ∧",
        "                    st.1.card = idx.k + row.val ∧",
        "                    st.2.card = idx.k + col.val ∧",
        "                    source = binaryOrbitOf",
        "                      (binaryWordOfSupport st.1) (binaryWordOfSupport st.2))).sum",
        "                (fun st => (-1 : Rat) ^",
        f"                  (idx.k - ({name_prefix}PairSameChoices idx st.1 st.2).card)))",
        "          rw [← Finset.sum_product']",
        "          simp [Finset.sum_filter]",
        "    _ = ∑ same ∈ Finset.range (idx.k + 1),",
        "          ∑ st ∈ base with classOf st = same,",
        "            (-1 : Rat) ^ (idx.k - classOf st) := by",
        "          exact (Finset.sum_fiberwise_of_maps_to hmaps",
        "            (fun st => (-1 : Rat) ^ (idx.k - classOf st))).symm",
        "    _ = ∑ same ∈ Finset.range (idx.k + 1),",
        "          (-1 : Rat) ^ (idx.k - same) *",
        f"            (({name_prefix}BlockCoeffSupportPairs idx row col source same).card : Rat) := by",
        "          apply Finset.sum_congr rfl",
        "          intro same _",
        f"          rw [← {name_prefix}BlockCoeffSupportPairs_eq_base_filter]",
        "          calc",
        f"            ∑ st ∈ {name_prefix}BlockCoeffSupportPairs idx row col source same,",
        "                (-1 : Rat) ^ (idx.k - classOf st) =",
        f"                ∑ _st ∈ {name_prefix}BlockCoeffSupportPairs idx row col source same,",
        "                  (-1 : Rat) ^ (idx.k - same) := by",
        "                  apply Finset.sum_congr rfl",
        "                  intro st hst",
        "                  have hsame : classOf st = same := by",
        f"                    rw [{name_prefix}BlockCoeffSupportPairs] at hst",
        "                    simp only [Finset.mem_filter] at hst",
        f"                    change ({name_prefix}PairSameChoices idx st.1 st.2).card = same",
        "                    exact hst.2.2.2.2.2.2",
        "                  rw [hsame]",
        "            _ = (-1 : Rat) ^ (idx.k - same) *",
        f"                (({name_prefix}BlockCoeffSupportPairs idx row col source same).card : Rat) := by",
        "                  rw [Finset.sum_const, nsmul_eq_mul]",
        "                  ring",
        "",
        "/--",
        "Linear-expression form of one scaled Schrijver block entry.  This is",
        "the blockwise target expected from a one-block compression congruence.",
        "-/",
        f"def {name_prefix}ScaledBlockEntryExpr",
        f"    (idx : BinaryBlockIndex {n})",
        "    (row col : BinaryBlockCoord idx) :",
        f"    LinExpr (BinaryOrbitIndex {n}) :=",
        f"  LinExpr.smul ({name_prefix}BlockScale idx)",
        f"    (binaryBlockEntryExpr {n} idx.k (fun source => LinExpr.var source)",
        "      row.val col.val)",
        "",
        f"theorem {name_prefix}ScaledBlockEntryExpr_eval",
        f"    (idx : BinaryBlockIndex {n})",
        "    (row col : BinaryBlockCoord idx)",
        f"    (x : BinaryOrbitIndex {n} -> Rat) :",
        f"    ({name_prefix}ScaledBlockEntryExpr idx row col).eval x =",
        f"      {name_prefix}BlockScale idx * binaryBlockForIndex x idx row col := by",
        f"  simp [{name_prefix}ScaledBlockEntryExpr, binaryBlockForIndex, binaryBlock]",
        "",
        f"theorem {name_prefix}BlockCompression_const_eq",
        f"    (idx : BinaryBlockIndex {n})",
        "    (row col : BinaryBlockCoord idx) :",
        f"    ({name_prefix}BlockCompressionEntryExpr idx row col).const =",
        f"      ({name_prefix}ScaledBlockEntryExpr idx row col).const := by",
        "  have hleft :",
        f"      ({name_prefix}BlockCompressionEntryExpr idx row col).const = 0 := by",
        f"    unfold {name_prefix}BlockCompressionEntryExpr",
        "    simp only [LinExpr.sum]",
        "    apply Finset.sum_eq_zero",
        "    intro u _",
        "    apply Finset.sum_eq_zero",
        "    intro v _",
        "    simp [LinExpr.smul, LinExpr.var]",
        "  have hblock :",
        f"      (binaryBlockEntryExpr {n} idx.k (fun source => LinExpr.var source)",
        "        row.val col.val).const = 0 := by",
        "    unfold binaryBlockEntryExpr",
        "    simp only [LinExpr.sum]",
        "    apply Finset.sum_eq_zero",
        "    intro t _",
        "    by_cases ht_i : t <= idx.k + row.val",
        "    · by_cases ht_j : t <= idx.k + col.val",
        f"      · by_cases hij : idx.k + row.val + (idx.k + col.val) <= {n} + t",
        "        · simp [ht_i, ht_j, hij, LinExpr.smul, LinExpr.var]",
        "        · simp [ht_i, ht_j, hij, LinExpr.constExpr]",
        "      · simp [ht_i, ht_j, LinExpr.constExpr]",
        "    · simp [ht_i, LinExpr.constExpr]",
        "  have hright :",
        f"      ({name_prefix}ScaledBlockEntryExpr idx row col).const = 0 := by",
        f"    simp [{name_prefix}ScaledBlockEntryExpr, LinExpr.smul, hblock]",
        "  rw [hleft, hright]",
        "",
        "/--",
        "Finite closed-form coefficient for the length-13 block compression.",
        "The parameter `same` counts the paired coordinates where both words",
        "choose the same side of the Schrijver pair; `source.t - same` is the",
        "intersection size contributed by the remaining coordinates.",
        "-/",
        f"def {name_prefix}BlockCoeffFormulaTermNat",
        "    (k row col : Nat) (sourceFin : Fin 560) (same : Nat) : Rat :=",
        f"  let source := binaryLength{length_name}OrbitOfFin sourceFin",
        f"  let free := {n} - 2 * k",
        "  let interFree := source.t - same",
        f"  if 2 * k <= {n} ∧ row < free + 1 ∧ col < free + 1 ∧",
        "      source.i = k + row ∧ source.j = k + col ∧ same <= k ∧",
        "      same <= source.t ∧ interFree <= free ∧ interFree <= row ∧",
        "      interFree <= col then",
        "    (-1 : Rat) ^ (k - same) *",
        "      (2 : Rat) ^ k *",
        "      (Nat.choose k same : Rat) *",
        "      (Nat.choose free interFree : Rat) *",
        "      (Nat.choose (free - interFree) (row - interFree) : Rat) *",
        "      (Nat.choose (free - row) (col - interFree) : Rat)",
        "  else",
        "    0",
        "",
        f"theorem {name_prefix}BlockCoeffFormulaTermNat_eq_signed_signless",
        f"    (idx : BinaryBlockIndex {n})",
        "    (row col : BinaryBlockCoord idx)",
        f"    (source : BinaryOrbitIndex {n}) (same : Nat) :",
        f"    {name_prefix}BlockCoeffFormulaTermNat",
        f"        idx.k row.val col.val ({name_prefix}OrbitToFin source) same =",
        "      (-1 : Rat) ^ (idx.k - same) *",
        f"        ({name_prefix}BlockCoeffSignlessTerm idx row col source same : Rat) := by",
        f"  have hsource := {name_prefix}OrbitOfFin_toFin source",
        f"  have hk : 2 * idx.k <= {n} := idx.hk",
        f"  have hrow : row.val < {n} - 2 * idx.k + 1 := row.isLt",
        f"  have hcol : col.val < {n} - 2 * idx.k + 1 := col.isLt",
        f"  unfold {name_prefix}BlockCoeffFormulaTermNat",
        f"    {name_prefix}BlockCoeffSignlessTerm {name_prefix}BlockCoeffSupportCondition",
        "  simp [hsource, hk, hrow, hcol]",
        "  by_cases hif : source.i = idx.k + row.val ∧",
        "      source.j = idx.k + col.val ∧",
        "      same <= idx.k ∧ same <= source.t ∧",
        f"      source.t <= {n} - 2 * idx.k + same ∧",
        "      source.t <= row.val + same ∧ source.t <= col.val + same",
        "  · simp [hif]",
        "    ring_nf",
        "  · simp [hif]",
        "",
        f"theorem {name_prefix}BlockCoeffFormulaTermNat_eq_signed_supportChoices_card",
        f"    (idx : BinaryBlockIndex {n})",
        "    (row col : BinaryBlockCoord idx)",
        f"    (source : BinaryOrbitIndex {n}) (same : Nat) :",
        f"    {name_prefix}BlockCoeffFormulaTermNat",
        f"        idx.k row.val col.val ({name_prefix}OrbitToFin source) same =",
        "      (-1 : Rat) ^ (idx.k - same) *",
        f"        (({name_prefix}BlockCoeffSupportChoices idx row col source same).card : Rat) := by",
        f"  rw [{name_prefix}BlockCoeffSupportChoices_card]",
        f"  exact {name_prefix}BlockCoeffFormulaTermNat_eq_signed_signless",
        "    idx row col source same",
        "",
        f"def {name_prefix}BlockCoeffFormulaNat",
        "    (k row col : Nat) (sourceFin : Fin 560) : Rat :=",
        f"  (Finset.range (k + 1)).sum (fun same =>",
        f"    {name_prefix}BlockCoeffFormulaTermNat k row col sourceFin same)",
        "",
        f"def {name_prefix}ScaledBetaCoeffNat",
        "    (k row col : Nat) (sourceFin : Fin 560) : Rat :=",
        f"  let source := {name_prefix}OrbitOfFin sourceFin",
        f"  if 2 * k <= {n} ∧ row < {n} - 2 * k + 1 ∧",
        f"      col < {n} - 2 * k + 1 ∧ source.i = k + row ∧",
        "      source.j = k + col then",
        f"    (2 : Rat) ^ k * betaCoeff {n} (k + row) (k + col) k source.t",
        "  else",
        "    0",
        "",
        f"theorem {name_prefix}BlockCoeffFormulaNat_eq_scaledBetaCoeffNat :",
        "    (forall k : Fin 7,",
        "      forall row : Fin 14,",
        "      forall col : Fin 14,",
        "      forall sourceFin : Fin 560,",
        f"        {name_prefix}BlockCoeffFormulaNat k.val row.val col.val sourceFin =",
        f"          {name_prefix}ScaledBetaCoeffNat k.val row.val col.val sourceFin) := by",
        "  native_decide",
        "",
        f"def {name_prefix}BlockCoeffFormula",
        f"    (idx : BinaryBlockIndex {n})",
        "    (row col : BinaryBlockCoord idx)",
        f"    (source : BinaryOrbitIndex {n}) : Rat :=",
        f"  {name_prefix}BlockCoeffFormulaNat idx.k row.val col.val",
        f"    ({name_prefix}OrbitToFin source)",
        "",
        f"def {name_prefix}ScaledBetaCoeff",
        f"    (idx : BinaryBlockIndex {n})",
        "    (row col : BinaryBlockCoord idx)",
        f"    (source : BinaryOrbitIndex {n}) : Rat :=",
        f"  {name_prefix}ScaledBetaCoeffNat idx.k row.val col.val",
        f"    ({name_prefix}OrbitToFin source)",
        "",
        f"theorem {name_prefix}ScaledBlockEntryExpr_coeff_eq_scaledBetaCoeff",
        f"    (idx : BinaryBlockIndex {n})",
        "    (row col : BinaryBlockCoord idx)",
        f"    (source : BinaryOrbitIndex {n}) :",
        f"    ({name_prefix}ScaledBlockEntryExpr idx row col).coeff source =",
        f"      {name_prefix}ScaledBetaCoeff idx row col source := by",
        f"  have hsource := {name_prefix}OrbitOfFin_toFin source",
        f"  have hk : 2 * idx.k ≤ {n} := idx.hk",
        f"  have hrow : row.val ≤ {n} - 2 * idx.k := Nat.lt_succ_iff.mp row.isLt",
        f"  have hcol : col.val ≤ {n} - 2 * idx.k := Nat.lt_succ_iff.mp col.isLt",
        f"  simp [{name_prefix}ScaledBlockEntryExpr, {name_prefix}ScaledBetaCoeff,",
        f"    {name_prefix}ScaledBetaCoeffNat, {name_prefix}BlockScale,",
        "    LinExpr.smul, binaryBlockEntryExpr_var_coeff, hsource, hk, hrow, hcol]",
        "",
        f"theorem {name_prefix}BlockCoeffFormula_eq_scaledBetaCoeff",
        f"    (idx : BinaryBlockIndex {n})",
        "    (row col : BinaryBlockCoord idx)",
        f"    (source : BinaryOrbitIndex {n}) :",
        f"    {name_prefix}BlockCoeffFormula idx row col source =",
        f"      {name_prefix}ScaledBetaCoeff idx row col source := by",
        f"  have hnat := {name_prefix}BlockCoeffFormulaNat_eq_scaledBetaCoeffNat",
        "    ⟨idx.k, by",
        "      have hk := idx.hk",
        "      omega⟩",
        "    ⟨row.val, by",
        "      have hk := idx.hk",
        "      have hrow := row.isLt",
        "      omega⟩",
        "    ⟨col.val, by",
        "      have hk := idx.hk",
        "      have hcol := col.isLt",
        "      omega⟩",
        f"    ({name_prefix}OrbitToFin source)",
        f"  have hsource := {name_prefix}OrbitOfFin_toFin source",
        f"  simpa [{name_prefix}BlockCoeffFormula,",
        f"    {name_prefix}ScaledBetaCoeff, {name_prefix}ScaledBetaCoeffNat,",
        f"    hsource, idx.hk, row.isLt, col.isLt] using hnat",
        "",
        f"theorem {name_prefix}BlockCompression_congruence_eq_of_coeff_eq",
        f"    (idx : BinaryBlockIndex {n})",
        f"    (x : BinaryOrbitIndex {n} -> Rat)",
        "    (hconst : forall row col,",
        f"      ({name_prefix}BlockCompressionEntryExpr idx row col).const =",
        f"        ({name_prefix}ScaledBlockEntryExpr idx row col).const)",
        "    (hcoeff : forall row col source,",
        f"      ({name_prefix}BlockCompressionEntryExpr idx row col).coeff source =",
        f"        ({name_prefix}ScaledBlockEntryExpr idx row col).coeff source) :",
        "    congruenceMatrix",
        f"      ({name_prefix}BlockCompressionMatrixFor idx)",
        "      (binaryTerwilligerMatrix x) =",
        f"        {name_prefix}BlockScale idx • binaryBlockForIndex x idx := by",
        "  ext row col",
        f"  rw [← {name_prefix}BlockCompressionEntryExpr_eval]",
        "  calc",
        f"    ({name_prefix}BlockCompressionEntryExpr idx row col).eval x =",
        f"        ({name_prefix}ScaledBlockEntryExpr idx row col).eval x := by",
        "          apply LinExpr.eval_eq_of_coeff_const_eq",
        "          · exact hconst row col",
        "          · intro source",
        "            exact hcoeff row col source",
        f"    _ = {name_prefix}BlockScale idx * binaryBlockForIndex x idx row col := by",
        f"          exact {name_prefix}ScaledBlockEntryExpr_eval idx row col x",
        "    _ = (fun row col =>",
        f"          {name_prefix}BlockScale idx * binaryBlockForIndex x idx row col)",
        "          row col := by rfl",
        "",
        f"noncomputable def {name_prefix}BlockScaledCompressionCertificateOfCoeff",
        f"    (idx : BinaryBlockIndex {n})",
        f"    (x : BinaryOrbitIndex {n} -> Rat)",
        "    (hconst : forall row col,",
        f"      ({name_prefix}BlockCompressionEntryExpr idx row col).const =",
        f"        ({name_prefix}ScaledBlockEntryExpr idx row col).const)",
        "    (hcoeff : forall row col source,",
        f"      ({name_prefix}BlockCompressionEntryExpr idx row col).coeff source =",
        f"        ({name_prefix}ScaledBlockEntryExpr idx row col).coeff source) :",
        "    BinaryBlockScaledCompressionCertificate idx",
        f"      ({name_prefix}BlockScale idx) x where",
        f"  scale_pos := {name_prefix}BlockScale_pos idx",
        f"  toMatrix := {name_prefix}BlockCompressionMatrixFor idx",
        f"  congruence_eq := {name_prefix}BlockCompression_congruence_eq_of_coeff_eq",
        "    idx x hconst hcoeff",
        "",
        f"noncomputable def {name_prefix}ScaledBlockCompressionCertificateOfCoeff",
        f"    (x : BinaryOrbitIndex {n} -> Rat)",
        "    (hconst : forall idx row col,",
        f"      ({name_prefix}BlockCompressionEntryExpr idx row col).const =",
        f"        ({name_prefix}ScaledBlockEntryExpr idx row col).const)",
        "    (hcoeff : forall idx row col source,",
        f"      ({name_prefix}BlockCompressionEntryExpr idx row col).coeff source =",
        f"        ({name_prefix}ScaledBlockEntryExpr idx row col).coeff source) :",
        "    BinaryBlockDiagonalizationScaledBlockCompressionCertificate",
        f"      {name_prefix}BlockScale x where",
        "  blockCert idx :=",
        f"    {name_prefix}BlockScaledCompressionCertificateOfCoeff",
        "      idx x (hconst idx) (hcoeff idx)",
        "",
        "/--",
        "Linear-expression form of the scaled block-diagonal target entry.  This",
        "is the right-hand side expected from the compression congruence.",
        "-/",
        f"def {name_prefix}ScaledBlockDiagonalEntryExpr",
        f"    (p q : Sigma (fun idx : BinaryBlockIndex {n} => BinaryBlockCoord idx)) :",
        f"    LinExpr (BinaryOrbitIndex {n}) :=",
        "  if p.1 = q.1 then",
        f"    LinExpr.smul ({name_prefix}BlockScale p.1)",
        f"      (binaryBlockEntryExpr {n} p.1.k (fun source => LinExpr.var source)",
        "        p.2.val q.2.val)",
        "  else",
        f"    LinExpr.constExpr (BinaryOrbitIndex {n}) 0",
        "",
        f"theorem {name_prefix}ScaledBlockDiagonalEntryExpr_eval",
        f"    (p q : Sigma (fun idx : BinaryBlockIndex {n} => BinaryBlockCoord idx))",
        f"    (x : BinaryOrbitIndex {n} -> Rat) :",
        f"    ({name_prefix}ScaledBlockDiagonalEntryExpr p q).eval x =",
        f"      binaryScaledBlockDiagonalMatrix {name_prefix}BlockScale x p q := by",
        "  rcases p with ⟨idx, row⟩",
        "  rcases q with ⟨idx2, col⟩",
        "  by_cases h : idx = idx2",
        "  · subst idx2",
        f"    simp [{name_prefix}ScaledBlockDiagonalEntryExpr,",
        "      binaryScaledBlockDiagonalMatrix, binaryBlockForIndex, binaryBlock]",
        f"  · simp [{name_prefix}ScaledBlockDiagonalEntryExpr, h,",
        "      binaryScaledBlockDiagonalMatrix, sigmaBlockDiagonal]",
        "",
        "end",
        "",
        "end GijswijtPolak2025",
        "end SDP",
        "end CoveringCodes",
        "",
    ]
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("n", type=int)
    parser.add_argument("--output", type=Path)
    args = parser.parse_args()

    rendered = generate_binary(args.n)
    if args.output is None:
        print(rendered, end="")
    else:
        args.output.write_text(rendered)


if __name__ == "__main__":
    main()
