#!/usr/bin/env python3
"""Emit the finite semantic bridge modules for the GP2025 K2 certificate.

The current quotient-certificate generator emits ``BridgeAtoms.lean`` from the
fresh expression export.  The finite length-13 bridge terms are independent of
the SDP certificate coefficients, so this helper installs the stable bridge
templates and rewrites them to import the current atom map directly.

The ``CompactBridge.lean`` template was recovered from the CoCo2026-src
``gp2025-sdp-formalization`` branch, commit
``f745cce30419fa26e4a1807dd6e78b700005a81c``.  The ``Bridge.lean`` template is
the later no-``native_decide`` version from the CoCo2026-src
``controller-wip-cache`` checkout, commit
``09f651ef732a004d854108b4fd54be77b45a8db1``.
"""

from __future__ import annotations

import argparse
from pathlib import Path


DEFAULT_MODULE_PREFIX = (
    "CoveringCodes.SDP.GijswijtPolak2025.Generated.BinaryK2_13_1"
)
DEFAULT_NAME = "binaryK2_13_1"
TEMPLATE_DIR = Path(__file__).resolve().parent / "templates" / "k2_13_1_bridge"


def module_prelude(imports: list[str], title: str) -> list[str]:
    lines = [f"import {module}" for module in imports]
    lines.extend(
        [
            "",
            "/-!",
            f"# {title}",
            "",
            "This file is generated by `gp2025_gen_lean_k2_bridge.py`.",
            "-/",
            "",
            "namespace CoveringCodes",
            "namespace SDP",
            "namespace GijswijtPolak2025",
            "",
            "noncomputable section",
            "",
            "set_option maxRecDepth 20000",
            "set_option maxHeartbeats 4000000",
            "",
        ]
    )
    return lines


def module_postlude() -> list[str]:
    return [
        "end",
        "",
        "end GijswijtPolak2025",
        "end SDP",
        "end CoveringCodes",
        "",
    ]


def write_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def render_template(template_name: str, module_prefix: str, name: str) -> str:
    template_path = TEMPLATE_DIR / template_name
    if not template_path.is_file():
        raise FileNotFoundError(f"missing bridge template: {template_path}")
    text = template_path.read_text(encoding="utf-8")
    text = text.replace(DEFAULT_MODULE_PREFIX, module_prefix)
    text = text.replace(DEFAULT_NAME, name)
    text = text.replace(
        f"import {module_prefix}.BridgeData",
        f"import {module_prefix}.BridgeAtoms",
    )
    return text


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output-dir", type=Path, required=True)
    parser.add_argument(
        "--module-prefix",
        default=DEFAULT_MODULE_PREFIX,
        help="Lean module prefix for generated K2 bridge modules",
    )
    parser.add_argument("--name", default=DEFAULT_NAME)
    args = parser.parse_args()

    if args.name != DEFAULT_NAME:
        raise SystemExit(
            "the K2 bridge templates are only validated for "
            f"--name {DEFAULT_NAME!r}"
        )

    args.output_dir.mkdir(parents=True, exist_ok=True)

    bridge_atoms = args.output_dir / "BridgeAtoms.lean"
    if not bridge_atoms.is_file():
        raise SystemExit(
            f"missing {bridge_atoms}; run gp2025_gen_lean_quotient_certificate.py first"
        )

    write_text(
        args.output_dir / "Bridge.lean",
        render_template("Bridge.lean", args.module_prefix, args.name),
    )
    write_text(
        args.output_dir / "CompactBridge.lean",
        render_template("CompactBridge.lean", args.module_prefix, args.name),
    )

    print(f"wrote bridge modules under {args.output_dir}")


if __name__ == "__main__":
    main()
